// Auto-generated by parse-project-docs.js
import { ProjectMetadata } from '../../project.factory';

export const metadata = {
  projectId: "architecture-college-plattform",
  featured: true,
  name: "Architecture College Platform",
  language: "Java",
  category: "backend",
  framework: "Spring Boot + Spring Cloud",
  version: "1.0.0",
  repositoryUrl: "https://github.com/alexisTrejo11/architecture-college-plattform",
  liveDemoUrl: "https://github.com/alexisTrejo11/architecture-college-plattform#deployed-topology-compose",
  description: "Production-style Spring Boot microservices monorepo for an architecture faculty. Seven domain services cover identity and access, student and teacher records, the academic catalog, class scheduling, enrollments, and grades—each with its own REST API and PostgreSQL database, JWT authentication, and registration through Eureka and Spring Cloud Config.\n\nThe platform is documented and runnable as deployed: Docker Compose brings up Postgres, MongoDB, RabbitMQ, Config Server, Eureka, Spring Boot Admin, and all business services. MongoDB and RabbitMQ support enrollment preload, grade projections, and scheduling integration where asynchronous or document-oriented workloads apply.",
  techStack: [
  "Java 17",
  "Spring Boot 3.3.x",
  "Spring Cloud 2023.0.3",
  "Spring Cloud Netflix Eureka",
  "Spring Cloud Config",
  "SpringDoc OpenAPI",
  "PostgreSQL",
  "Docker",
  "Spring Web",
  "Spring Data JPA",
  "Spring Data MongoDB",
  "MongoDB",
  "RabbitMQ",
  "JWT"
],
  status: "deployed",
  createdAt: new Date("2026-01-01T00:00:00.000Z"),
  updatedAt: new Date("2026-06-09T00:00:00.000Z"),
} satisfies ProjectMetadata;
