// Auto-generated by parse-project-docs.js
import { ProjectCodeShowCase } from '../../../../../../core/models/project-docs.models';

export const codeShowcase = {
  "codeExamples": [
    {
      "id": "showtime-entity",
      "title": "Showtime Entity — Business Rules",
      "description": "Domain validation for price, duration, and scheduling constraints.",
      "category": "Domain",
      "tags": [
        "Domain-Driven Design",
        "Business Rules",
        "Validation"
      ],
      "files": [
        {
          "name": "showtime.py",
          "path": "app/showtime/domain/entities/showtime.py",
          "language": "python",
          "explanation": "Price must be strictly between $3 and $50; duration 30–300 min; schedule within 30 days and not in the past.",
          "content": "def _validate_price(self):\n    MAX_LIMIT_PRICE = Decimal(\"50.00\")\n    MIN_LIMIT_PRICE = Decimal(\"3.00\")\n    if not (MIN_LIMIT_PRICE < self.price < MAX_LIMIT_PRICE):\n        raise InvalidShowtimePriceError(\n            self.price, MIN_LIMIT_PRICE, MAX_LIMIT_PRICE\n        )\n\ndef _validate_schedule_date_no_too_far(self):\n    MAX_DAYS_START_DATE_ALLOWED = 30\n    now_utc = datetime.now(timezone.utc)\n    future_limit_date = now_utc + timedelta(days=MAX_DAYS_START_DATE_ALLOWED)\n    start_time_utc = self._normalize_datetime_to_utc(self.start_time)\n    if start_time_utc > future_limit_date:\n        raise ShowtimeSchedulingError(\n            f\"Showtime exceeds {MAX_DAYS_START_DATE_ALLOWED} days limit\"\n        )\n"
        }
      ]
    },
    {
      "id": "showtime-lifecycle",
      "title": "Showtime Lifecycle Methods",
      "description": "State transitions for draft, launch, cancel, restore, and soft delete.",
      "category": "Domain",
      "tags": [
        "State Management",
        "Business Logic"
      ],
      "files": [
        {
          "name": "showtime.py",
          "path": "app/showtime/domain/entities/showtime.py",
          "language": "python",
          "explanation": "Each transition validates current state; only DRAFT showtimes can be soft-deleted.",
          "content": "def mark_as_launchable(self):\n    if self.status != ShowtimeStatus.DRAFT:\n        raise ValidationError(\"Showtime is not draft can't be launched\")\n    self.status = ShowtimeStatus.UPCOMING\n    self.updated_at = datetime.now(timezone.utc)\n\ndef cancel(self):\n    if self.deleted_at is not None:\n        raise ShowtimeCancellationError(self.id if self.id else 0)\n    if self.status == ShowtimeStatus.COMPLETED:\n        raise ShowtimeCancellationError(self.id if self.id else 0)\n    self.status = ShowtimeStatus.CANCELLED\n    self.updated_at = datetime.now(timezone.utc)\n\ndef mark_as_deleted(self):\n    if not self._is_deletable():\n        raise ShowtimeDeletionError(self.id if self.id else 0)\n    self.deleted_at = datetime.now(timezone.utc)\n"
        }
      ]
    },
    {
      "id": "showtime-seat",
      "title": "ShowtimeSeat Entity",
      "description": "Seat reservation with take/leave and timestamp tracking.",
      "category": "Domain",
      "tags": [
        "Seat Reservation",
        "Domain Entities"
      ],
      "files": [
        {
          "name": "showtime_seat.py",
          "path": "app/showtime/domain/entities/showtime_seat.py",
          "language": "python",
          "explanation": "taken_at presence indicates reservation; leave() clears user association.",
          "content": "def is_taken(self) -> bool:\n    return self.taken_at is not None\n\ndef take(self):\n    if self.is_taken():\n        raise ValueError(\"Seat Already Taken\")\n    self.taken_at = datetime.now(timezone.utc)\n\ndef leave(self):\n    self.taken_at = None\n    self.user_id = None\n"
        }
      ]
    },
    {
      "id": "showtime-controller",
      "title": "Showtime Controller — RBAC & Rate Limits",
      "description": "FastAPI route with dependency injection, JWT roles, and SlowAPI limiter.",
      "category": "Presentation",
      "tags": [
        "FastAPI",
        "REST API",
        "Dependency Injection"
      ],
      "files": [
        {
          "name": "showtime_controller.py",
          "path": "app/showtime/infrastructure/api/showtime_controller.py",
          "language": "python",
          "explanation": "Launch endpoint requires admin/manager; limited to 10 requests per minute.",
          "content": "@router.post(\"/{showtime_id}/launch\", response_model=ShowtimeDetailResponse)\n@limiter.limit(\"10/minute\")\nasync def launch_showtime(\n    showtime_id: int,\n    request: Request,\n    use_case: LaunchShowtimeUseCase = Depends(\n        showtime_use_cases.launch_showtime_use_case\n    ),\n    _: AuthUserContext = Depends(require_roles(\"admin\", \"manager\")),\n):\n    showtime = await use_case.execute(showtime_id)\n    return ShowtimeDetailResponse.model_validate(showtime)\n"
        }
      ]
    },
    {
      "id": "buffer-times",
      "title": "Buffer Time Calculation",
      "description": "Pre-show and post-show buffer durations for scheduling.",
      "category": "Domain",
      "tags": [
        "Business Logic",
        "Time Management"
      ],
      "files": [
        {
          "name": "showtime.py",
          "path": "app/showtime/domain/entities/showtime.py",
          "language": "python",
          "explanation": "50 min pre-show (10 cleaning + 40 commercials); 30 min post-cleaning; +10 optional post-credits.",
          "content": "_EXTRA_DURATIONS: ClassVar = {\n    \"initial_cleaning\": 10,\n    \"initial_commercials\": 40,\n    \"post_credits_scene\": 10,\n    \"post_cleaning\": 30,\n}\n\n@classmethod\ndef get_buffered_extra_times(cls, include_post_credits_scene: bool = False):\n    pre_buffer_minutes = (\n        cls._EXTRA_DURATIONS[\"initial_cleaning\"]\n        + cls._EXTRA_DURATIONS[\"initial_commercials\"]\n    )\n    post_buffer_minutes = cls._EXTRA_DURATIONS[\"post_cleaning\"]\n    if include_post_credits_scene:\n        post_buffer_minutes += cls._EXTRA_DURATIONS[\"post_credits_scene\"]\n    return {\n        \"pre_buffer\": timedelta(minutes=pre_buffer_minutes),\n        \"post_buffer\": timedelta(minutes=post_buffer_minutes),\n    }\n"
        }
      ]
    },
    {
      "id": "app-lifespan",
      "title": "Application Lifespan — Startup Checks",
      "description": "FastAPI lifespan hook for Postgres validation, Redis init, and graceful shutdown.",
      "category": "Configuration",
      "tags": [
        "FastAPI",
        "Startup",
        "Redis"
      ],
      "files": [
        {
          "name": "main.py",
          "path": "main.py",
          "language": "python",
          "explanation": "Validates DB connectivity and initializes cache before serving traffic.",
          "content": "@asynccontextmanager\nasync def lifespan(app: FastAPI):\n    logger.info(\"Starting up Billboard Service...\")\n    await run_postgres_startup_check(engine)\n    await init_cache()\n    yield\n    logger.info(\"Shutting down Billboard Service...\")\n    await close_cache()\n"
        }
      ]
    },
    {
      "id": "movie-entity",
      "title": "Movie Entity — Exhibition Logic",
      "description": "Domain model with is_showing() based on projection date range.",
      "category": "Domain",
      "tags": [
        "Domain-Driven Design",
        "Validation"
      ],
      "files": [
        {
          "name": "entities.py",
          "path": "app/movies/domain/entities.py",
          "language": "python",
          "explanation": "is_active checks deleted_at; is_showing uses projection window.",
          "content": "@property\ndef is_active(self) -> bool:\n    return self.deleted_at is None\n\ndef is_showing(self, on_date: Optional[date] = None) -> bool:\n    if on_date is None:\n        on_date = date.today()\n    return self.projection_start_date <= on_date <= self.projection_end_date\n"
        }
      ]
    },
    {
      "id": "theater-capacity",
      "title": "Theater Capacity Rules",
      "description": "Type-driven min/max capacity validation in domain entity.",
      "category": "Domain",
      "tags": [
        "Business Rules",
        "Theater"
      ],
      "files": [
        {
          "name": "theater.py",
          "path": "app/theater/domain/theater.py",
          "language": "python",
          "explanation": "IMAX 150–300, VIP 10–50; raises InvalidCapacityError on violation.",
          "content": "CAPACITY_RULES: ClassVar = {\n    TheaterType.IMAX: {\"min\": 150, \"max\": 300},\n    TheaterType.VIP: {\"min\": 10, \"max\": 50},\n}\n\ndef validate_capacity(self):\n    rules = self.CAPACITY_RULES.get(self.theater_type, {})\n    if rules and not (rules[\"min\"] <= self.capacity <= rules[\"max\"]):\n        raise InvalidCapacityError(\n            f\"Capacity {self.capacity} invalid for {self.theater_type}\"\n        )\n"
        }
      ]
    },
    {
      "id": "movie-controller",
      "title": "Movie Controller — Active Exhibition",
      "description": "Paginated endpoint for movies currently showing.",
      "category": "Presentation",
      "tags": [
        "FastAPI",
        "Pagination"
      ],
      "files": [
        {
          "name": "movie_controllers.py",
          "path": "app/movies/infrastructure/api/movie_controllers.py",
          "language": "python",
          "explanation": "Use case injected via Depends; 60/min rate limit.",
          "content": "@router.get(\"/active/\", response_model=PaginatedMovieResponse)\n@limiter.limit(\"60/minute\")\nasync def get_movies_in_exhibition(\n    use_case: Annotated[GetMoviesInExhitionUseCase, Depends(...)],\n    request: Request,\n    offset: Annotated[int, Query(ge=0)] = 0,\n    limit: Annotated[int, Query(ge=1, le=100)] = 10,\n):\n    params = PaginationParams(offset=offset, limit=limit)\n    page = await use_case.execute(params)\n    return PaginatedMovieResponse.from_page(page)\n"
        }
      ]
    },
    {
      "id": "grpc-servicer",
      "title": "gRPC Catalog Servicer",
      "description": "IsMovieActive RPC used by billboard-service for validation.",
      "category": "Integration",
      "tags": [
        "gRPC",
        "Inter-service"
      ],
      "files": [
        {
          "name": "catalog_server.py",
          "path": "app/grpc/catalog_server.py",
          "language": "python",
          "explanation": "Opens async session per RPC; returns is_active from domain entity.",
          "content": "async def IsMovieActive(self, request, context):\n    async with AsyncSessionLocal() as session:\n        repo = SQLAlchemyMovieRepository(session)\n        movie = await repo.find_by_id(request.movie_id)\n        return catalog_pb2.IsMovieActiveResponse(\n            is_active=bool(movie and movie.is_active)\n        )\n"
        }
      ]
    },
    {
      "id": "app-lifespan",
      "title": "Lifespan — gRPC Co-Startup",
      "description": "FastAPI lifespan starts gRPC server alongside REST.",
      "category": "Configuration",
      "tags": [
        "FastAPI",
        "gRPC"
      ],
      "files": [
        {
          "name": "main.py",
          "path": "main.py",
          "language": "python",
          "explanation": "gRPC server stopped gracefully on shutdown (5s grace).",
          "content": "@asynccontextmanager\nasync def lifespan(app: FastAPI):\n    await run_postgres_startup_check(engine)\n    grpc_server = create_catalog_grpc_server()\n    await grpc_server.start()\n    app.state.grpc_server = grpc_server\n    yield\n    await grpc_server.stop(grace=5)\n"
        }
      ]
    },
    {
      "id": "theater-maintenance",
      "title": "Theater Maintenance Mode",
      "description": "Maintenance forces deactivation; cannot activate while in maintenance.",
      "category": "Domain",
      "tags": [
        "State Management"
      ],
      "files": [
        {
          "name": "theater.py",
          "path": "app/theater/domain/theater.py",
          "language": "python",
          "explanation": "enter_maintenance sets maintenance_mode and deactivates theater.",
          "content": "def enter_maintenance(self):\n    self.maintenance_mode = True\n    self.deactivate()\n\ndef activate(self):\n    if self.maintenance_mode:\n        raise TheaterMaintenanceError(\n            \"Cannot activate theater while in maintenance mode\"\n        )\n    self.is_active = True\n"
        }
      ]
    },
    {
      "id": "product-entity",
      "title": "Product Entity — Business Validation",
      "description": "Pydantic entity with ProductId value object and ProductValidator.",
      "category": "Domain",
      "tags": [
        "DDD",
        "Pydantic",
        "Validation"
      ],
      "files": [
        {
          "name": "product.py",
          "path": "app/products/domain/entities/product.py",
          "language": "python",
          "explanation": "model_validator runs ProductValidator; soft delete via deleted_at.",
          "content": "@model_validator(mode=\"after\")\ndef _run_business_validation(self) -> \"Product\":\n    ProductValidator.validate_product(self)\n    return self\n\ndef restore(self) -> \"Product\":\n    self.deleted_at = None\n    return self\n"
        }
      ]
    },
    {
      "id": "combo-discount",
      "title": "Combo Entity — Discount Rules",
      "description": "Combo with discount_percentage bounded 0–100 and line items.",
      "category": "Domain",
      "tags": [
        "Combos",
        "Pricing"
      ],
      "files": [
        {
          "name": "combo.py",
          "path": "app/combos/domain/entities/combo.py",
          "language": "python",
          "explanation": "Decimal coercion for price and discount; items list for bundle composition.",
          "content": "class Combo(BaseModel):\n    id: ComboId\n    name: str = Field(..., min_length=1, max_length=200)\n    price: Decimal = Field(..., gt=Decimal(\"0\"))\n    discount_percentage: Decimal = Field(\n        default=Decimal(\"0\"), ge=Decimal(\"0\"), le=Decimal(\"100\")\n    )\n    items: List[ComboItem] = Field(default_factory=list)\n    deleted_at: Optional[datetime] = None\n"
        }
      ]
    },
    {
      "id": "promotion-domain",
      "title": "Promotion — Domain Validation",
      "description": "Promotion entity with creation validation and UTC timestamps.",
      "category": "Domain",
      "tags": [
        "Promotions",
        "Business Logic"
      ],
      "files": [
        {
          "name": "promotion.py",
          "path": "app/promotions/domain/entities/promotion.py",
          "language": "python",
          "explanation": "validate_creation_fields enforces name, dates, and applicable IDs.",
          "content": "class Promotion(BaseModel):\n    name: str\n    promotion_type: PromotionType\n    rule: dict = Field(default_factory=dict)\n    start_date: datetime\n    end_date: datetime\n    applicable_product_ids: List[ProductId] = []\n    max_uses: Optional[int] = None\n    current_uses: int = 0\n\ndef validate_creation_fields(self):\n    if len(self.name) < 3:\n        raise InvalidPromotionDataError(\"Invalid promotion name\", ...)\n"
        }
      ]
    },
    {
      "id": "product-controller",
      "title": "Product Controller — CQRS + RBAC",
      "description": "Search endpoint wiring query DTO to use case with rate limit.",
      "category": "Presentation",
      "tags": [
        "FastAPI",
        "CQRS"
      ],
      "files": [
        {
          "name": "product_controller.py",
          "path": "app/products/infrastructure/api/controllers/product_controller.py",
          "language": "python",
          "explanation": "ProductSearchQuery converted to SearchProductsQuery with pagination.",
          "content": "@router.get(\"/\", response_model=ProductPaginatedResponse)\n@limiter.limit(\"60/minute\")\nasync def search_products(\n    request: Request,\n    search_params: ProductSearchQuery = Depends(),\n    usecase: ProductUseCases = Depends(get_product_use_cases),\n):\n    params = _search_products_query_from_request(search_params)\n    return await usecase.search_products(params)\n"
        }
      ]
    },
    {
      "id": "grpc-servicer",
      "title": "gRPC Product Lookup",
      "description": "ConcessionCatalogGrpcServicer resolves product including soft-deleted fallback.",
      "category": "Integration",
      "tags": [
        "gRPC"
      ],
      "files": [
        {
          "name": "concession_catalog_servicer.py",
          "path": "app/grpc/services/concession_catalog_servicer.py",
          "language": "python",
          "explanation": "Parses UUID via ProductId.from_string; returns exists flag in reply.",
          "content": "async def GetProductById(self, request, context):\n    product_id = await self._parse_id(\n        raw_id=request.id, parser=ProductId.from_string, ...\n    )\n    async with self._session_factory() as session:\n        repo = SQLAlchemyProductRepository(session)\n        product = await repo.find_by_id(product_id)\n        if product is None:\n            product = await repo.find_deleted_by_id(product_id)\n        return self._build_product_reply(product)\n"
        }
      ]
    },
    {
      "id": "lifespan-cache",
      "title": "Lifespan — Redis Init",
      "description": "FastAPI startup initializes Postgres check and Redis cache.",
      "category": "Configuration",
      "tags": [
        "FastAPI",
        "Redis"
      ],
      "files": [
        {
          "name": "main.py",
          "path": "main.py",
          "language": "python",
          "explanation": "init_cache on startup; close_cache on shutdown (unlike catalog-service).",
          "content": "@asynccontextmanager\nasync def lifespan(app: FastAPI):\n    await run_postgres_startup_check(engine)\n    await init_cache()\n    logger.info(\"Redis initialized.\")\n    yield\n    await close_cache()\n"
        }
      ]
    },
    {
      "id": "employee-entity",
      "title": "Employee Entity — State Transitions",
      "description": "Domain methods for terminate, suspend, reactivate, and promote with status guards.",
      "category": "Domain",
      "tags": [
        "Domain-Driven Design",
        "State Management"
      ],
      "files": [
        {
          "name": "entities.py",
          "path": "app/employees/domain/entities.py",
          "language": "python",
          "explanation": "Each transition validates current employment_status before mutating.",
          "content": "def terminate(self, termination_date: date | None = None) -> None:\n    if self.employment_status == EmploymentStatus.TERMINATED:\n        raise InvalidEmployeeOperationError(\"Employee is already terminated\")\n    self.employment_status = EmploymentStatus.TERMINATED\n    self.termination_date = termination_date or date.today()\n\ndef suspend(self) -> None:\n    if self.employment_status != EmploymentStatus.ACTIVE:\n        raise InvalidEmployeeOperationError(\"Cannot suspend — not ACTIVE\")\n    self.employment_status = EmploymentStatus.SUSPENDED\n\ndef promote(self, new_position: str, new_salary: Decimal, new_role=None) -> None:\n    if self.employment_status == EmploymentStatus.TERMINATED:\n        raise InvalidEmployeeOperationError(\"Cannot promote terminated employee\")\n    self.position = new_position\n    self.salary = new_salary\n"
        }
      ]
    },
    {
      "id": "hire-use-case",
      "title": "Hire Employee Use Case",
      "description": "Application layer enforces email uniqueness before creating domain entity.",
      "category": "Application",
      "tags": [
        "Use Case Pattern",
        "Clean Architecture"
      ],
      "files": [
        {
          "name": "hire_employee.py",
          "path": "app/employees/application/use_cases/hire_employee.py",
          "language": "python",
          "explanation": "Repository port checked for existing email; Employee.create builds domain object.",
          "content": "async def execute(self, command: HireEmployeeCommand) -> Employee:\n    existing = await self._repository.get_by_email(command.email)\n    if existing:\n        raise EmployeeAlreadyExistsError(command.email)\n    employee = Employee.create({...})\n    return await self._repository.create(employee)\n"
        }
      ]
    },
    {
      "id": "vacation-workflow",
      "title": "Vacation Request Approval",
      "description": "Domain entity guards status transitions for manager approve/reject.",
      "category": "Domain",
      "tags": [
        "Workflow",
        "Business Rules"
      ],
      "files": [
        {
          "name": "entities.py",
          "path": "app/vacations/domain/entities.py",
          "language": "python",
          "explanation": "Only PENDING requests can be approved or rejected; reviewer metadata recorded.",
          "content": "def approve(self, reviewer_id: int, comment: str | None = None) -> None:\n    if self.status != VacationStatus.PENDING:\n        raise VacationRequestInvalidStatusError(\"Only pending can be approved\")\n    self.status = VacationStatus.APPROVED\n    self.reviewed_by = reviewer_id\n    self.reviewed_at = datetime.now()\n"
        }
      ]
    },
    {
      "id": "cache-service",
      "title": "Upstash-Compatible Cache Service",
      "description": "JSON cache with prefixed keys and graceful Redis unavailability.",
      "category": "Infrastructure",
      "tags": [
        "Redis",
        "Caching"
      ],
      "files": [
        {
          "name": "cache_config.py",
          "path": "app/config/cache_config.py",
          "language": "python",
          "explanation": "init_cache pings Redis on startup; failures log warning and continue without cache.",
          "content": "async def init_cache() -> None:\n    _redis = Redis.from_url(settings.REDIS_URL, decode_responses=True)\n    if settings.REDIS_VALIDATE_ON_STARTUP:\n        await _redis.ping()\n    cache_service = CacheService()\n"
        }
      ]
    },
    {
      "id": "use-case-container",
      "title": "Employee Use Cases Facade",
      "description": "Single DI entry point aggregating all employee use cases.",
      "category": "Application",
      "tags": [
        "Dependency Injection",
        "Facade"
      ],
      "files": [
        {
          "name": "container.py",
          "path": "app/employees/application/use_cases/container.py",
          "language": "python",
          "explanation": "Controllers depend on EmployeeUseCases rather than individual use case classes.",
          "content": "class EmployeeUseCases:\n    def __init__(self, repository: EmployeeRepository):\n        self._hire = HireEmployeeUseCase(repository)\n        self._terminate = TerminateEmployeeUseCase(repository)\n        # ...\n\n    async def hire(self, command: HireEmployeeCommand) -> Employee:\n        return await self._hire.execute(command)\n"
        }
      ]
    },
    {
      "id": "lifespan",
      "title": "FastAPI Lifespan — Startup Checks",
      "description": "Validates Postgres and Redis before serving traffic.",
      "category": "Infrastructure",
      "tags": [
        "FastAPI",
        "Health"
      ],
      "files": [
        {
          "name": "main.py",
          "path": "main.py",
          "language": "python",
          "explanation": "run_postgres_startup_check and init_cache run in lifespan before yield.",
          "content": "@asynccontextmanager\nasync def lifespan(app: FastAPI):\n    await run_postgres_startup_check(engine)\n    await init_cache()\n    yield\n    await close_cache()\n"
        }
      ]
    },
    {
      "id": "notification-aggregate",
      "title": "Notification Aggregate — Lifecycle",
      "description": "Domain aggregate with mark_as_sent, mark_as_failed, and attention tracking.",
      "category": "Domain",
      "tags": [
        "DDD",
        "Aggregate",
        "Pydantic"
      ],
      "files": [
        {
          "name": "models.py",
          "path": "app/notification/domain/entities/models.py",
          "language": "python",
          "explanation": "State transitions update status timestamps and clear error fields on success.",
          "content": "def mark_as_sent(self, sent_at: Optional[datetime] = None) -> None:\n    self.status = NotificationStatus.SENT\n    self.sent_at = sent_at or datetime.now(timezone.utc)\n    self.failed_at = None\n    self.error_details = None\n\ndef mark_as_failed(self, error_details: str, ...) -> None:\n    self.status = NotificationStatus.FAILED\n    self.failed_at = failed_at or datetime.now(timezone.utc)\n    self.error_details = error_details\n\ndef mark_attention_open(self) -> None:\n    self.is_important = True\n    self.attention_status = NotificationAttentionStatus.OPEN\n"
        }
      ]
    },
    {
      "id": "create-usecase",
      "title": "Create Notification Use Case",
      "description": "Persists aggregate then invokes SendingService for delivery.",
      "category": "Application",
      "tags": [
        "Use Case",
        "CQRS"
      ],
      "files": [
        {
          "name": "notification_usecases.py",
          "path": "app/notification/application/usecases/notification_usecases.py",
          "language": "python",
          "explanation": "Builds Notification from CreateNotificationCommand, saves, sends, updates status.",
          "content": "class CreateNotificationUseCase:\n    async def execute(self, command: CreateNotificationCommand):\n        notification = Notification(\n            notification_type=command.notification_type,\n            recipient=command.recipient,\n            content=command.content,\n            channel=command.channel,\n            ...\n        )\n        await self.repository.save(notification)\n        await self.sending_service.send(notification)\n"
        }
      ]
    },
    {
      "id": "notification-controller",
      "title": "Notification Controller",
      "description": "Thin FastAPI router delegating to use cases via Depends.",
      "category": "Presentation",
      "tags": [
        "FastAPI",
        "REST"
      ],
      "files": [
        {
          "name": "notification_controller.py",
          "path": "app/notification/presentation/notification_controller.py",
          "language": "python",
          "explanation": "List endpoint supports rich query filters and pagination.",
          "content": "router = APIRouter(prefix=\"/api/v2/notifications\")\n\n@router.post(\"\", response_model=NotificationResponse, status_code=201)\nasync def create_notification(\n    command: CreateNotificationCommand,\n    usecase: CreateNotificationUseCase = Depends(...),\n):\n    return await usecase.execute(command)\n\n@router.get(\"\", response_model=NotificationListResponse)\nasync def list_notifications(\n    notification_type: NotificationType | None = None,\n    channel: NotificationChannel | None = None,\n    user_id: str | None = None,\n    limit: int = Query(10, ge=1, le=100),\n    ...\n):\n    ...\n"
        }
      ]
    },
    {
      "id": "kafka-consumer",
      "title": "Kafka Consumer Loop",
      "description": "Poll loop extracts ProcessIncomingNotificationEventCommand from raw JSON.",
      "category": "Integration",
      "tags": [
        "Kafka",
        "Events"
      ],
      "files": [
        {
          "name": "kafka_config.py",
          "path": "app/config/kafka_config.py",
          "language": "python",
          "explanation": "Consumer started as asyncio task when KAFKA_CONSUMER_ENABLED.",
          "content": "def start_kafka_consumer_tasks(stop: asyncio.Event):\n    if not settings.KAFKA_CONSUMER_ENABLED:\n        return []\n    return [asyncio.create_task(_run_incoming_notifications_loop(stop))]\n\n# Inside loop: poll → parse event_id → usecase.execute(command)\n"
        }
      ]
    },
    {
      "id": "email-service",
      "title": "Email Service — Jinja2 Templates",
      "description": "Renders HTML template by NotificationType and sends via SMTP.",
      "category": "Infrastructure",
      "tags": [
        "Email",
        "Jinja2"
      ],
      "files": [
        {
          "name": "mail_service.py",
          "path": "app/notification/infrastructure/email/mail_service.py",
          "language": "python",
          "explanation": "Templates from html_teamplates.py; uses sync smtplib.",
          "content": "async def send(self, notification: Notification) -> None:\n    html_content = self._render_template(\n        notification_type=notification.notification_type,\n        template_data=notification.content.data or {},\n    )\n    self._send_email(\n        to_email=notification.recipient.email,\n        subject=notification.content.subject,\n        html_content=html_content,\n    )\n"
        }
      ]
    },
    {
      "id": "app-lifespan",
      "title": "Lifespan — Mongo + Kafka + Registry",
      "description": "Startup connects Mongo, optional registry, and Kafka consumer tasks.",
      "category": "Configuration",
      "tags": [
        "FastAPI",
        "Lifespan"
      ],
      "files": [
        {
          "name": "main.py",
          "path": "main.py",
          "language": "python",
          "explanation": "Graceful consumer cancel and registry heartbeat stop on shutdown.",
          "content": "@asynccontextmanager\nasync def lifespan(app: FastAPI):\n    if settings.REGISTRY_ENABLED:\n        registry_client = RegistryMicroservice()\n        await registry_client.perform_registry()\n    await connect_to_mongo()\n    if settings.KAFKA_CONSUMER_ENABLED:\n        app.state.kafka_consumer_tasks = start_kafka_consumer_tasks(stop_ev)\n    yield\n    # cancel consumer tasks, stop registry, close mongo\n"
        }
      ]
    },
    {
      "id": "payment-aggregate",
      "title": "Payment Aggregate — Lifecycle",
      "description": "Domain aggregate with create, complete, refund, cancel, and domain events.",
      "category": "Domain",
      "tags": [
        "DDD",
        "Aggregate",
        "Events"
      ],
      "files": [
        {
          "name": "payment.py",
          "path": "app/payments/domain/entities/payment.py",
          "language": "python",
          "explanation": "Enforces refund window, emits PaymentCompleted/PaymentRefunded events.",
          "content": "class Payment(AggregateRoot):\n    id: PaymentId\n    user_id: UserId\n    amount: Money\n    status: PaymentStatus\n\n    def complete(self, transaction_reference=None):\n        if not self.can_be_completed():\n            raise PaymentAlreadyProcessedException(...)\n        self.status = PaymentStatus.COMPLETED\n        self.completed_at = datetime.now(timezone.utc)\n        self._add_event(PaymentCompleted(...))\n\n    def refund(self, amount: Money, reason: str):\n        if not self.can_be_refunded():\n            raise PaymentNotRefundableException(...)\n        self._add_event(PaymentRefunded(...))\n"
        }
      ]
    },
    {
      "id": "kafka-publisher",
      "title": "Kafka Payment Events Publisher",
      "description": "Infrastructure adapter publishing domain events to payment.events topic.",
      "category": "Infrastructure",
      "tags": [
        "Kafka",
        "Event-Driven"
      ],
      "files": [
        {
          "name": "kafka_payment_events.py",
          "path": "app/payments/infrastructure/messaging/kafka_payment_events.py",
          "language": "python",
          "explanation": "Wraps kafka-python producer with JSON envelope (event_type, service, payload).",
          "content": "class KafkaPaymentEventsPublisher(PaymentEventsPublisher):\n    async def publish(self, event_name, payload, key=None):\n        message = {\n            \"event_type\": event_name,\n            \"service\": settings.SERVICE_NAME,\n            \"payload\": payload,\n        }\n        value = json.dumps(message, default=str).encode(\"utf-8\")\n        self._producer.send(topic=self._topic, key=key, value=value)\n"
        }
      ]
    },
    {
      "id": "customer-controller",
      "title": "Customer Payment Controller",
      "description": "Role-scoped router for purchases, initiate/confirm, and stored cards.",
      "category": "Presentation",
      "tags": [
        "FastAPI",
        "REST"
      ],
      "files": [
        {
          "name": "customer_payment_controller.py",
          "path": "app/payments/presentation/controllers/customer_payment_controller.py",
          "language": "python",
          "explanation": "Note /consessions path typo; strict get_current_user on all routes.",
          "content": "router = APIRouter(prefix=\"/api/v1/payments/customers\")\n\n@router.post(\"/initiate\", response_model=InitiatePaymentResponse)\nasync def initiate_payment(body, user=Depends(get_current_user), ...):\n    ...\n\n@router.post(\"/tickets\", status_code=201)\nasync def purchase_tickets(body: TicketPurchaseRequest, ...):\n    payment = await use_case.purchase_tickets(body.to_command(str(user.id)))\n    return PaymentResponse.from_entity(payment)\n\n@router.post(\"/consessions\", status_code=201)  # typo: consessions\nasync def purchase_consessions(...):\n    ...\n"
        }
      ]
    },
    {
      "id": "stripe-gateway",
      "title": "Stripe Payment Gateway Adapter",
      "description": "Implements PaymentGateway port for PaymentIntent create/confirm.",
      "category": "Infrastructure",
      "tags": [
        "Stripe",
        "Adapter"
      ],
      "files": [
        {
          "name": "stripe_gateway.py",
          "path": "app/payments/infrastructure/gateways/stripe_gateway.py",
          "language": "python",
          "explanation": "Maps domain Money and metadata to Stripe SDK calls.",
          "content": "class StripePaymentGateway(PaymentGateway):\n    async def create_payment_intent(self, amount, currency, metadata):\n        intent = stripe.PaymentIntent.create(\n            amount=int(amount * 100),\n            currency=currency.lower(),\n            metadata=metadata,\n        )\n        return intent.id\n"
        }
      ]
    },
    {
      "id": "main-lifespan",
      "title": "FastAPI Lifespan Wiring",
      "description": "Startup checks Postgres, optional Redis/Kafka/registry; mounts four routers.",
      "category": "Integration",
      "tags": [
        "FastAPI",
        "Lifespan"
      ],
      "files": [
        {
          "name": "main.py",
          "path": "main.py",
          "language": "python",
          "explanation": "perfom_registry typo; CORS allow_origins wildcard.",
          "content": "@asynccontextmanager\nasync def lifespan(app: FastAPI):\n    await check_postgres_connection()\n    if settings.REDIS_VALIDATE_ON_STARTUP:\n        await init_cache()\n    if settings.REGISTRY_ENABLED:\n        await perfom_registry()  # typo\n    if settings.KAFKA_CONSUMER_ENABLED:\n        await start_kafka_consumer_tasks()\n    yield\n    ...\n\napp.include_router(payment_methods_router)\napp.include_router(customer_payment_router)\napp.include_router(staff_payment_router)\napp.include_router(admin_payment_router)\n"
        }
      ]
    },
    {
      "id": "buy-tickets",
      "title": "Buy Tickets Command",
      "description": "POST /buy with strict rate limit and use case delegation.",
      "category": "Presentation",
      "tags": [
        "FastAPI",
        "CQRS"
      ],
      "files": [
        {
          "name": "ticket_command_controller.py",
          "path": "app/ticket/infrastructure/api/ticket_command_controller.py",
          "language": "python",
          "explanation": "Command router separate from queries; 10/min limit on purchase.",
          "content": "router = APIRouter(prefix=\"/api/v2/tickets\", tags=[\"Tickets — commands\"])\n\n@router.post(\"/buy\", response_model=TicketBuyedResponse, status_code=201)\n@limiter.limit(\"10/minute\")\nasync def buy_tickets(request: Request, ticket_data: BuyTicketsRequest, ...):\n    return await use_cases.execute(ticket_data)\n"
        }
      ]
    },
    {
      "id": "search-tickets",
      "title": "Search Tickets Query",
      "description": "GET / with filter params via SearchTicketParams dependency.",
      "category": "Presentation",
      "tags": [
        "FastAPI",
        "Query"
      ],
      "files": [
        {
          "name": "ticket_query_controller.py",
          "path": "app/ticket/infrastructure/api/ticket_query_controller.py",
          "language": "python",
          "explanation": "Query router shares prefix but different OpenAPI tag.",
          "content": "@router.get(\"/\", response_model=List[TicketResponse])\n@limiter.limit(\"60/minute\")\nasync def search_tickets(\n    request: Request,\n    params: Annotated[SearchTicketParams, Depends(search_ticket_params)],\n    use_case: GetTicketsByCriteriaUseCase = Depends(...),\n):\n    return await use_case.execute(params)\n"
        }
      ]
    },
    {
      "id": "main-lifespan",
      "title": "Lifespan — Mongo, Kafka, Registry",
      "description": "Connects Mongo, optional registry and Kafka consumers; no Redis init.",
      "category": "Integration",
      "tags": [
        "Lifespan",
        "Kafka"
      ],
      "files": [
        {
          "name": "main.py",
          "path": "main.py",
          "language": "python",
          "explanation": "Logs \"Wallet Service registered\" on registry success (typo).",
          "content": "@asynccontextmanager\nasync def lifespan(app: FastAPI):\n    await run_postgres_startup_check(engine)\n    if settings.REGISTRY_ENABLED:\n        registered, instance_id = await registry_client.perfom_registry()\n    await connect_to_mongo()\n    if settings.KAFKA_CONSUMER_ENABLED:\n        app.state.kafka_consumer_tasks = start_kafka_consumer_tasks(stop_ev)\n    yield\n    # cancel consumers, close mongo, stop registry\n"
        }
      ]
    },
    {
      "id": "purchase-quote",
      "title": "Purchase Quote from Replica",
      "description": "Read-only pricing without seat hold.",
      "category": "Application",
      "tags": [
        "Mongo",
        "Quote"
      ],
      "files": [
        {
          "name": "ticket_query_controller.py",
          "path": "app/ticket/infrastructure/api/ticket_query_controller.py",
          "language": "python",
          "explanation": "seat_count query param 1-100; 120/min rate limit.",
          "content": "@router.get(\"/quotes/showtime/{showtime_id}\", response_model=PurchaseQuoteResponse)\nasync def get_purchase_quote(showtime_id: int, seat_count: int = Query(1, ge=1, le=100), ...):\n    return await use_case.execute(showtime_id, seat_count)\n"
        }
      ]
    },
    {
      "id": "jwt-middleware",
      "title": "Optional JWT Middleware",
      "description": "Validates Bearer when present; most ticket routes do not require it.",
      "category": "Security",
      "tags": [
        "JWT"
      ],
      "files": [
        {
          "name": "jwt_security.py",
          "path": "app/shared/middleware/jwt_security.py",
          "language": "python",
          "explanation": "Same optional pattern as notification-service.",
          "content": "class JwtAuthMiddleware(BaseHTTPMiddleware):\n    async def dispatch(self, request, call_next):\n        if not request.headers.get(\"Authorization\"):\n            return await call_next(request)\n        claims = decode_jwt_token(token)\n        request.state.current_user = AuthUserContext.from_claims(claims)\n        return await call_next(request)\n"
        }
      ]
    },
    {
      "id": "auth-signup",
      "title": "Auth Controller — Signup",
      "description": "Public registration endpoint delegating to AuthUseCasesContainer.",
      "category": "Presentation",
      "tags": [
        "FastAPI",
        "Auth"
      ],
      "files": [
        {
          "name": "auth_controllers.py",
          "path": "app/auth/infrastructure/api/auth_controllers.py",
          "language": "python",
          "explanation": "Result pattern maps domain errors to HTTP 400.",
          "content": "router = APIRouter(prefix=\"/api/v2/auth\", tags=[\"auth\"])\n\n@router.post(\"/signup\", response_model=UserResponse, status_code=201)\nasync def signup(request_body: SignUpRequest, use_cases=Depends(...)):\n    result = await use_cases.signup.execute(request_body)\n    if not result.is_success():\n        raise HTTPException(status_code=400, detail=result.get_error_message())\n    return result.get_data()\n"
        }
      ]
    },
    {
      "id": "jwt-middleware",
      "title": "Optional JWT Middleware",
      "description": "Attaches current_user to request.state when Bearer token valid.",
      "category": "Security",
      "tags": [
        "JWT",
        "Middleware"
      ],
      "files": [
        {
          "name": "auth_middleware.py",
          "path": "app/middleware/auth_middleware.py",
          "language": "python",
          "explanation": "Missing Authorization header passes through without auth context.",
          "content": "async def jwt_auth_middleware(request, call_next):\n    request.state.current_user = None\n    auth_header = request.headers.get(\"Authorization\", \"\")\n    if not auth_header:\n        return await call_next(request)\n    claims = decode_jwt_token(token)\n    request.state.current_user = AuthUserContext.from_claims(claims)\n    return await call_next(request)\n"
        }
      ]
    },
    {
      "id": "grpc-servicer",
      "title": "gRPC UsersService Servicer",
      "description": "Internal directory lookups by id, email, or phone.",
      "category": "Integration",
      "tags": [
        "gRPC",
        "Directory"
      ],
      "files": [
        {
          "name": "servicer.py",
          "path": "app/config/grpc/servicer.py",
          "language": "python",
          "explanation": "Imports use app.grpc.* namespace — verify module layout matches entrypoint.",
          "content": "class UsersGrpcServicer(users_pb2_grpc.UsersServiceServicer):\n    async def GetUserById(self, request, context):\n        async with AsyncSessionLocal() as session:\n            repo = SQLAlchemyUserRepository(session)\n            user = await repo.get_by_id(int(request.id))\n            if not user:\n                return users_pb2.GetUserResponse(success=False, message=\"User not found\")\n            return users_pb2.GetUserResponse(success=True, user=user_to_proto(user))\n"
        }
      ]
    },
    {
      "id": "profile-update",
      "title": "Profile Update Use Case",
      "description": "Self-service partial profile patch for authenticated user.",
      "category": "Application",
      "tags": [
        "Profile",
        "Use Case"
      ],
      "files": [
        {
          "name": "controllers.py",
          "path": "app/profile/infrastructure/controllers.py",
          "language": "python",
          "explanation": "GET/PATCH on /api/v2/profiles with get_logged_user dependency.",
          "content": "@router.patch(\"/\", response_model=ProfileResponse)\nasync def update_my_profile(\n    update_data: ProfileUpdate,\n    user: User = Depends(get_logged_user),\n    usecase: UpdateProfileUseCase = Depends(update_profile_use_case),\n):\n    return await usecase.execute(user, update_data)\n"
        }
      ]
    },
    {
      "id": "main-lifespan",
      "title": "Lifespan — Postgres, Redis, Kafka",
      "description": "Startup checks and cache init; event publisher on app.state.",
      "category": "Integration",
      "tags": [
        "Lifespan",
        "Redis"
      ],
      "files": [
        {
          "name": "main.py",
          "path": "main.py",
          "language": "python",
          "explanation": "init_cache() always called; Kafka publisher created at import time.",
          "content": "@asynccontextmanager\nasync def lifespan(app: FastAPI):\n    await run_postgres_startup_check(engine)\n    await init_cache()\n    yield\n    shutdown_event_publisher()\n    await close_cache()\n\napp.state.event_publisher = create_event_publisher()\napp.middleware(\"http\")(jwt_auth_middleware)\n"
        }
      ]
    },
    {
      "id": "wallet-aggregate",
      "title": "Wallet Aggregate — Credit & Debit",
      "description": "Domain methods for add_credit and buy_product with transaction recording.",
      "category": "Domain",
      "tags": [
        "DDD",
        "Aggregate Root"
      ],
      "files": [
        {
          "name": "wallet.py",
          "path": "app/wallet/domain/entities/wallet.py",
          "language": "python",
          "explanation": "buy_product debits via remove_credit; amounts stored positive with transaction type indicating direction.",
          "content": "def buy_credit(self, payment_details, amount: Money) -> WalletTransaction:\n    self.add_credit(amount)\n    return self._create_transaction(\n        amount, TransactionType.ADD_CREDIT, payment_details\n    )\n\ndef buy_product(self, payment_details, amount: Charge) -> WalletTransaction:\n    self.remove_credit(amount)\n    transaction_amount = Money(amount=amount.amount, currency=amount.currency)\n    return self._create_transaction(\n        transaction_amount, TransactionType.BUY_PRODUCT, payment_details\n    )\n"
        }
      ]
    },
    {
      "id": "domain-validator",
      "title": "Wallet Domain Validator",
      "description": "Per-currency credit limits and insufficient-funds check.",
      "category": "Domain",
      "tags": [
        "Business Rules",
        "Validation"
      ],
      "files": [
        {
          "name": "validators.py",
          "path": "app/wallet/domain/validators.py",
          "language": "python",
          "explanation": "USD and MXN ranges enforced; debit compares Charge against wallet balance.",
          "content": "def validate_credit_decrease(self, amount: Charge) -> None:\n    if amount.amount <= Decimal(\"0\"):\n        raise InvalidTransactionAmountError(\"Charge amount must be positive.\")\n    charge_as_money = Money(amount=amount.amount, currency=amount.currency)\n    if self.wallet.balance < charge_as_money:\n        raise InsufficientFundsError(\"Insufficient funds.\")\n"
        }
      ]
    },
    {
      "id": "init-wallet",
      "title": "Init Wallet For User",
      "description": "Creates wallet after validating user exists and has no existing wallet.",
      "category": "Application",
      "tags": [
        "Use Case"
      ],
      "files": [
        {
          "name": "wallet_command_use_cases.py",
          "path": "app/wallet/application/use_cases/wallet_command_use_cases.py",
          "language": "python",
          "explanation": "UserInternalService port + UserWalletConflict guard.",
          "content": "async def execute(self, command: CreateWalletCommand) -> Wallet:\n    await self._validate_user(command.user_id)\n    new_wallet = Wallet.create(command.user_id)\n    return await self._wallet_repo.create(new_wallet)\n"
        }
      ]
    },
    {
      "id": "use-case-facade",
      "title": "WalletUseCases Facade",
      "description": "Single DI entry for all wallet operations in controllers.",
      "category": "Application",
      "tags": [
        "Dependency Injection"
      ],
      "files": [
        {
          "name": "container.py",
          "path": "app/wallet/presentation/container.py",
          "language": "python",
          "explanation": "Wires repositories, user service, and event publisher into use cases.",
          "content": "class WalletUseCases:\n    def __init__(self, wallet_repo, transaction_repository, user_service, event_publisher):\n        self._add_credit = AddCreditUseCase(...)\n        self._pay = PayWithWalletUseCase(...)\n        self._create_wallet = InitWalletForUserUseCase(...)\n"
        }
      ]
    },
    {
      "id": "kafka-publisher",
      "title": "Kafka Wallet Event Publisher",
      "description": "Publishes JSON wallet events when KAFKA_ENABLED.",
      "category": "Infrastructure",
      "tags": [
        "Kafka",
        "Events"
      ],
      "files": [
        {
          "name": "wallet_producer.py",
          "path": "app/wallet/infrastructure/message/wallet_producer.py",
          "language": "python",
          "explanation": "Sync KafkaProducer wrapped for async use; topic from KAFKA_WALLET_EVENTS_TOPIC.",
          "content": "class WalletEventProducerImpl(WalletEventPublisher):\n    async def publish_event(self, wallet, transaction, event_type):\n        payload = {\"event\": event_type.value, \"wallet_id\": str(wallet.id.value)}\n        await asyncio.to_thread(self._kafka.send_json, payload)\n"
        }
      ]
    },
    {
      "id": "auth-context",
      "title": "JWT Auth User Context",
      "description": "UUID subject and staff role checking for management routes.",
      "category": "Security",
      "tags": [
        "JWT",
        "RBAC"
      ],
      "files": [
        {
          "name": "auth.py",
          "path": "app/shared/auth.py",
          "language": "python",
          "explanation": "sub claim parsed as UUID; staff roles admin/manager/employee.",
          "content": "STAFF_ROLE_NAMES = frozenset({\"admin\", \"manager\", \"employee\"})\n\nasync def require_staff_user(user: AuthUserContext = Depends(get_current_user)):\n    if not is_staff_user(user):\n        raise HTTPException(status_code=403, detail=\"Requires staff role\")\n    return user\n"
        }
      ]
    }
  ]
} as unknown as ProjectCodeShowCase;
