// Auto-generated by parse-project-docs.js
import { InfrastructureModel } from '../../../../../../core/models/project-docs.models';

export const infrastructure = {
  "deploymentLayers": [
    {
      "name": "Edge & Load Balancing",
      "color": "#4A90E2",
      "components": [
        {
          "name": "NGINX",
          "icon": "🌐",
          "description": "TLS termination and load balancing across app replicas (local compose)"
        },
        {
          "name": "Health probes",
          "icon": "🟢",
          "description": "GET /health for container and orchestrator checks"
        }
      ]
    },
    {
      "name": "Application",
      "color": "#7ED321",
      "components": [
        {
          "name": "FastAPI REST API",
          "icon": "🌐",
          "description": "Uvicorn-served HTTP on port 8000"
        },
        {
          "name": "JWT Auth Middleware",
          "icon": "🔒",
          "description": "Token validation and role extraction"
        },
        {
          "name": "Rate Limiting",
          "icon": "🚦",
          "description": "SlowAPI middleware on all routes"
        }
      ]
    },
    {
      "name": "Data",
      "color": "#F5A623",
      "components": [
        {
          "name": "PostgreSQL",
          "icon": "🗄️",
          "description": "billboard schema — showtimes, showtime_seats (Alembic migrations)"
        },
        {
          "name": "Redis",
          "icon": "⚡",
          "description": "Cache with REDIS_URL and optional startup validation"
        }
      ]
    },
    {
      "name": "Integration",
      "color": "#D0021B",
      "components": [
        {
          "name": "gRPC Catalog Client",
          "icon": "🔗",
          "description": "GRPC_CATALOG_TARGET for movie/theater validation"
        },
        {
          "name": "Kafka Publisher",
          "icon": "📤",
          "description": "Optional event streaming (KAFKA_ENABLED)"
        }
      ]
    },
    {
      "name": "Edge & Load Balancing",
      "color": "#4A90E2",
      "components": [
        {
          "name": "NGINX",
          "icon": "🌐",
          "description": "TLS and load balancing in local compose (port 8443)"
        },
        {
          "name": "Health probes",
          "icon": "🟢",
          "description": "GET /health and Docker HEALTHCHECK on :8000"
        }
      ]
    },
    {
      "name": "Application",
      "color": "#7ED321",
      "components": [
        {
          "name": "FastAPI REST",
          "icon": "🌐",
          "description": "Port 8000 — movies, cinemas, theaters, seats"
        },
        {
          "name": "gRPC Server",
          "icon": "🔗",
          "description": "Port 50055 — CatalogService RPCs"
        },
        {
          "name": "JWT + Rate Limit",
          "icon": "🔒",
          "description": "JwtAuthMiddleware + SlowAPI"
        }
      ]
    },
    {
      "name": "Data",
      "color": "#F5A623",
      "components": [
        {
          "name": "PostgreSQL",
          "icon": "🗄️",
          "description": "cinema_catalog DB, Alembic migrations"
        },
        {
          "name": "Redis",
          "icon": "⚡",
          "description": "REDIS_URL — init optional at startup"
        }
      ]
    },
    {
      "name": "Messaging",
      "color": "#D0021B",
      "components": [
        {
          "name": "Kafka",
          "icon": "📤",
          "description": "Optional producers/consumers (KAFKA_ENABLED, KAFKA_CONSUMER_ENABLED)"
        }
      ]
    },
    {
      "name": "Gateway",
      "color": "#795548",
      "components": [
        {
          "name": "NGINX",
          "icon": "🌐",
          "description": "Load balances app-1/2/3 on ports 80/443"
        },
        {
          "name": "CORS",
          "icon": "🔒",
          "description": "localhost allowlist in main.py"
        }
      ]
    },
    {
      "name": "Application",
      "color": "#2196F3",
      "components": [
        {
          "name": "REST instances (app-1/2/3)",
          "icon": "⚙️",
          "description": "Gunicorn + UvicornWorker on :8000"
        },
        {
          "name": "gRPC (app-grpc)",
          "icon": "🔗",
          "description": "python -m app.grpc.server on :50051"
        },
        {
          "name": "migrate (profile tools)",
          "icon": "📋",
          "description": "One-shot Alembic upgrade"
        }
      ]
    },
    {
      "name": "Data",
      "color": "#336791",
      "components": [
        {
          "name": "PostgreSQL",
          "icon": "🗄️",
          "description": "Host port 5431 in local compose"
        },
        {
          "name": "Redis",
          "icon": "⚡",
          "description": "Host port 6378 in local compose"
        }
      ]
    },
    {
      "name": "Edge & Load Balancing",
      "color": "#4A90E2",
      "components": [
        {
          "name": "NGINX (local)",
          "icon": "🌐",
          "description": "TLS on port 8447, HTTP redirect on 8084 — load balances 3 app replicas"
        },
        {
          "name": "EC2 public endpoint (production)",
          "icon": "☁️",
          "description": "Docker exposes API_PORT (default 8000); optional ALB in front — placeholder"
        },
        {
          "name": "Health probes",
          "icon": "🟢",
          "description": "GET /health and Docker HEALTHCHECK on :8000"
        }
      ]
    },
    {
      "name": "Application",
      "color": "#7ED321",
      "components": [
        {
          "name": "FastAPI REST API",
          "icon": "🌐",
          "description": "Uvicorn-served HTTP on port 8000 inside container"
        },
        {
          "name": "JWT Auth",
          "icon": "🔒",
          "description": "PyJWT Bearer validation; admin/manager/employee roles"
        },
        {
          "name": "Rate Limiting",
          "icon": "🚦",
          "description": "SlowAPI middleware on all routes"
        },
        {
          "name": "Alembic migrations",
          "icon": "📦",
          "description": "One-off migrate task or RUN_MIGRATIONS_ON_START on first replica"
        }
      ]
    },
    {
      "name": "Data (managed cloud)",
      "color": "#F5A623",
      "components": [
        {
          "name": "Amazon RDS PostgreSQL",
          "icon": "🗄️",
          "description": "POSTGRES_HOST=your-rds-endpoint.rds.amazonaws.com; POSTGRES_SSL_MODE=require recommended"
        },
        {
          "name": "Upstash Redis",
          "icon": "⚡",
          "description": "REDIS_URL=rediss://default:<token>@<region>.upstash.io:6379; consumed from EC2 instance .env"
        }
      ]
    },
    {
      "name": "Edge",
      "color": "#4A90E2",
      "components": [
        {
          "name": "Load Balancer / API Gateway",
          "icon": "🌐",
          "description": "TLS termination and optional JWT enforcement"
        },
        {
          "name": "Rate Limiter",
          "icon": "🚦",
          "description": "SlowAPI 60/min per IP at app layer"
        }
      ]
    },
    {
      "name": "Application",
      "color": "#50C878",
      "components": [
        {
          "name": "FastAPI + Uvicorn",
          "icon": "⚙️",
          "description": "REST API and in-process Kafka consumer tasks"
        },
        {
          "name": "Service Registry Client",
          "icon": "📋",
          "description": "Optional REGISTRY_ENABLED heartbeat"
        }
      ]
    },
    {
      "name": "Data & Messaging",
      "color": "#FFD700",
      "components": [
        {
          "name": "MongoDB",
          "icon": "🗄️",
          "description": "notification_db database"
        },
        {
          "name": "Redis",
          "icon": "⚡",
          "description": "REDIS_URL cache backend"
        },
        {
          "name": "Kafka",
          "icon": "📤",
          "description": "Incoming and outbound notification topics"
        }
      ]
    },
    {
      "name": "External Providers",
      "color": "#9B59B6",
      "components": [
        {
          "name": "SMTP Server",
          "icon": "📧",
          "description": "SMTP_HOST/PORT/TLS credentials"
        },
        {
          "name": "Twilio API",
          "icon": "💬",
          "description": "SMS when TWILIO_ENABLED"
        },
        {
          "name": "User Service HTTP",
          "icon": "👤",
          "description": "USER_DIRECTORY_BASE_URL contact lookup"
        }
      ]
    },
    {
      "name": "Edge",
      "color": "#4A90E2",
      "components": [
        {
          "name": "nginx",
          "icon": "🌐",
          "description": "TLS termination, load balance across app-1..3 (ports 80/443)"
        },
        {
          "name": "Rate Limiter",
          "icon": "🚦",
          "description": "SlowAPI at application layer"
        }
      ]
    },
    {
      "name": "Application",
      "color": "#50C878",
      "components": [
        {
          "name": "FastAPI + Uvicorn (x3)",
          "icon": "⚙️",
          "description": "HTTP API replicas; app-1 runs migrations on start"
        },
        {
          "name": "app-grpc",
          "icon": "🔗",
          "description": "serve-grpc entrypoint on GRPC_PORT 50051"
        },
        {
          "name": "Service Registry Client",
          "icon": "📋",
          "description": "Optional REGISTRY_ENABLED registration"
        }
      ]
    },
    {
      "name": "Data & Messaging",
      "color": "#FFD700",
      "components": [
        {
          "name": "PostgreSQL",
          "icon": "🗄️",
          "description": "Host port 5431 → 5432 in docker-compose"
        },
        {
          "name": "Redis",
          "icon": "⚡",
          "description": "Host port 6378 → 6379"
        },
        {
          "name": "Kafka",
          "icon": "📤",
          "description": "External or compose profile — not in default compose file"
        }
      ]
    },
    {
      "name": "External Providers",
      "color": "#9B59B6",
      "components": [
        {
          "name": "Stripe API",
          "icon": "💳",
          "description": "STRIPE_SECRET_KEY / webhook secret"
        },
        {
          "name": "Billboard gRPC",
          "icon": "🎬",
          "description": "GRPC_BILLBOARD_TARGET for purchase assertions"
        }
      ]
    },
    {
      "name": "Edge",
      "color": "#4A90E2",
      "components": [
        {
          "name": "nginx",
          "icon": "🌐",
          "description": "Load balances app-1..3 (ports 80/443)"
        },
        {
          "name": "Rate Limiter",
          "icon": "🚦",
          "description": "Per-endpoint SlowAPI limits"
        }
      ]
    },
    {
      "name": "Application",
      "color": "#50C878",
      "components": [
        {
          "name": "FastAPI + Uvicorn/Gunicorn",
          "icon": "⚙️",
          "description": "Three HTTP replicas"
        },
        {
          "name": "Kafka Consumer Tasks",
          "icon": "📥",
          "description": "In-process asyncio consumers when enabled"
        },
        {
          "name": "Registry Client",
          "icon": "📋",
          "description": "Optional service registration"
        }
      ]
    },
    {
      "name": "Data & Messaging",
      "color": "#FFD700",
      "components": [
        {
          "name": "PostgreSQL",
          "icon": "🗄️",
          "description": "Host port 5431 → 5432"
        },
        {
          "name": "MongoDB",
          "icon": "🍃",
          "description": "Host port 27017 (default)"
        },
        {
          "name": "Redis",
          "icon": "⚡",
          "description": "Host port 6378 → 6379"
        },
        {
          "name": "Kafka",
          "icon": "📤",
          "description": "External broker; example compose in kafka-bridge profile"
        }
      ]
    },
    {
      "name": "Edge",
      "color": "#4A90E2",
      "components": [
        {
          "name": "nginx",
          "icon": "🌐",
          "description": "Load balances app-1..3 (ports 80/443)"
        },
        {
          "name": "Rate Limiter",
          "icon": "🚦",
          "description": "SlowAPI 30/min at app layer"
        }
      ]
    },
    {
      "name": "Application",
      "color": "#50C878",
      "components": [
        {
          "name": "Gunicorn + Uvicorn workers",
          "icon": "⚙️",
          "description": "HTTP replicas via docker-entrypoint.sh serve"
        },
        {
          "name": "app-grpc",
          "icon": "🔗",
          "description": "serve-grpc → UsersService on 50051"
        }
      ]
    },
    {
      "name": "Data",
      "color": "#FFD700",
      "components": [
        {
          "name": "PostgreSQL",
          "icon": "🗄️",
          "description": "Host port 5431 → 5432"
        },
        {
          "name": "Redis",
          "icon": "⚡",
          "description": "Host port 6378 → 6379"
        }
      ]
    },
    {
      "name": "Edge & Load Balancing",
      "color": "#4A90E2",
      "components": [
        {
          "name": "NGINX (local)",
          "icon": "🌐",
          "description": "Ports 80/443 — load balances app-1, app-2, app-3"
        },
        {
          "name": "EC2 public endpoint (production)",
          "icon": "☁️",
          "description": "API_PORT default 8000; optional ALB — placeholder"
        },
        {
          "name": "Health probes",
          "icon": "🟢",
          "description": "GET /health and Docker HEALTHCHECK"
        }
      ]
    },
    {
      "name": "Application",
      "color": "#7ED321",
      "components": [
        {
          "name": "FastAPI REST",
          "icon": "🌐",
          "description": "Port 8000 — staff, customer, management routes"
        },
        {
          "name": "gRPC placeholder",
          "icon": "🔗",
          "description": "app-grpc on port 50051 (local) — no RPC handlers yet"
        },
        {
          "name": "JWT + Rate Limit",
          "icon": "🔒",
          "description": "PyJWT + SlowAPI 30/min default"
        },
        {
          "name": "Service registry (optional)",
          "icon": "📡",
          "description": "REGISTRY_ENABLED heartbeat to REGISTRY_ADMIN_URL"
        }
      ]
    },
    {
      "name": "Data (managed cloud)",
      "color": "#F5A623",
      "components": [
        {
          "name": "Amazon RDS PostgreSQL",
          "icon": "🗄️",
          "description": "POSTGRES_HOST=your-rds-endpoint.rds.amazonaws.com; SSL recommended"
        },
        {
          "name": "Upstash Redis",
          "icon": "⚡",
          "description": "rediss://default:<token>@<region>.upstash.io:6379 from EC2 .env"
        }
      ]
    }
  ],
  "dockerFiles": [
    {
      "service": "billboard-service",
      "description": "Multi-stage Python 3.13 image with non-root user and built-in healthcheck.",
      "content": "FROM python:3.13-slim AS builder\nWORKDIR /app\nCOPY requirements.txt ./\nRUN python -m venv /opt/venv && /opt/venv/bin/pip install -r requirements.txt\n\nFROM python:3.13-slim AS runtime\nWORKDIR /app\nCOPY --from=builder /opt/venv /opt/venv\nCOPY . .\nUSER app\nEXPOSE 8000\nHEALTHCHECK CMD python -c \"import urllib.request; urllib.request.urlopen('http://127.0.0.1:8000/health')\"\nCMD [\"/app/docker/docker-entrypoint.sh\", \"serve\"]\n"
    },
    {
      "service": "local-stack",
      "description": "docker-compose.local.yml — Postgres 16, Redis 7, 2 app replicas, NGINX on 8443.",
      "content": "services:\n  db:\n    image: postgres:16-alpine\n  redis:\n    image: redis:7-alpine\n  app-1:\n    build: { context: .., dockerfile: docker/dockerfile }\n  app-2:\n    image: billboard-service:local\n  nginx:\n    ports: [\"8443:443\"]\n"
    },
    {
      "service": "catalog-service",
      "description": "Multi-stage Python 3.13 image, non-root user, healthcheck on /health.",
      "content": "FROM python:3.13-slim AS builder\nWORKDIR /app\nCOPY requirements.txt ./\nRUN python -m venv /opt/venv && /opt/venv/bin/pip install -r requirements.txt\n\nFROM python:3.13-slim AS runtime\nWORKDIR /app\nCOPY --from=builder /opt/venv /opt/venv\nCOPY . .\nUSER app\nEXPOSE 8000\nHEALTHCHECK CMD python -c \"urllib.request.urlopen('http://127.0.0.1:8000/health')\"\nCMD [\"/app/docker/docker-entrypoint.sh\", \"serve\"]\n"
    },
    {
      "service": "local-stack",
      "description": "docker-compose.local.yml — Postgres 16, Redis 7, 2 replicas, NGINX, gRPC 50055.",
      "content": "services:\n  db:\n    image: postgres:16-alpine\n    ports: [\"5434:5432\"]\n  redis:\n    image: redis:7-alpine\n    ports: [\"6381:6379\"]\n  app-1:\n    build: { context: .., dockerfile: docker/dockerfile }\n    environment:\n      GRPC_PORT: 50055\n  nginx:\n    ports: [\"8443:443\"]\n"
    },
    {
      "service": "concession-service",
      "description": "Multi-stage Python 3.13 image, non-root user, healthcheck.",
      "content": "FROM python:3.13-slim AS builder\nCOPY requirements.txt ./\nRUN python -m venv /opt/venv && /opt/venv/bin/pip install -r requirements.txt\n\nFROM python:3.13-slim AS runtime\nCOPY --from=builder /opt/venv /opt/venv\nCOPY . .\nUSER app\nEXPOSE 8000\nCMD [\"/app/docker/docker-entrypoint.sh\", \"serve\"]\n"
    },
    {
      "service": "docker-compose",
      "description": "Stack with db, redis, app-1/2/3, app-grpc, nginx.",
      "content": "services:\n  db:\n    image: postgres:16-alpine\n    ports: [\"5431:5432\"]\n  redis:\n    image: redis:7-alpine\n    ports: [\"6378:6379\"]\n  app-grpc:\n    command: [\"/app/docker/docker-entrypoint.sh\", \"serve-grpc\"]\n    ports: [\"50051:50051\"]\n  nginx:\n    ports: [\"80:80\", \"443:443\"]\n"
    },
    {
      "service": "employee-service",
      "description": "Multi-stage Python 3.13 image with non-root user and built-in healthcheck.",
      "content": "FROM python:3.13-slim AS builder\nWORKDIR /app\nCOPY requirements.txt ./\nRUN python -m venv /opt/venv && /opt/venv/bin/pip install -r requirements.txt\n\nFROM python:3.13-slim AS runtime\nWORKDIR /app\nCOPY --from=builder /opt/venv /opt/venv\nCOPY . .\nUSER app\nEXPOSE 8000\nHEALTHCHECK CMD python -c \"import urllib.request; urllib.request.urlopen('http://127.0.0.1:8000/health')\"\nCMD [\"/app/docker/docker-entrypoint.sh\", \"serve\"]\n"
    },
    {
      "service": "local-stack",
      "description": "docker-compose.local.yml — Postgres 16, Redis 7, 3 app replicas, NGINX on 8447.",
      "content": "services:\n  db:\n    image: postgres:16-alpine\n    ports: [\"5436:5432\"]\n  redis:\n    image: redis:7-alpine\n    ports: [\"6384:6379\"]\n  app-1:\n    build: { context: .., dockerfile: docker/dockerfile }\n    environment: { RUN_MIGRATIONS_ON_START: \"1\" }\n  app-2:\n    image: employee-service:local\n  app-3:\n    image: employee-service:local\n  nginx:\n    ports: [\"8084:80\", \"8447:443\"]\n"
    },
    {
      "service": "production (EC2)",
      "description": "docker-compose.prod.yml — application container only; RDS + Upstash from .env.",
      "content": "services:\n  app:\n    build: { context: .., dockerfile: docker/dockerfile }\n    env_file: [../.env]\n    ports: [\"${API_PORT:-8000}:8000\"]\n    command: [\"/app/docker/docker-entrypoint.sh\", \"serve\"]\n"
    },
    {
      "service": "notification-service",
      "description": "Referenced in README; Dockerfile/docker-compose not present in repository at time of doc generation — run locally with uvicorn or add compose file.",
      "content": "# Suggested local run (no committed Dockerfile):\npip install -r requirements.txt\nalembic upgrade head  # if migrations added\nuvicorn main:app --host 0.0.0.0 --port 8000\n\n# Production pattern (from deprecated docs):\nFROM python:3.13-slim\nCOPY requirements.txt .\nRUN pip install -r requirements.txt\nCOPY . .\nEXPOSE 8000\nCMD [\"uvicorn\", \"main:app\", \"--host\", \"0.0.0.0\", \"--port\", \"8000\"]\n"
    },
    {
      "service": "payment-service",
      "description": "Multi-replica HTTP + separate gRPC + nginx load balancer.",
      "content": "# docker/docker-compose.yml (summary)\nservices:\n  db:        postgres:16  → host 5431\n  redis:     redis:7      → host 6378\n  app-1:     payment-service:local (migrations on start)\n  app-2:     payment-service:local\n  app-3:     payment-service:local\n  app-grpc:  payment-service:local serve-grpc → 50051\n  nginx:     load balances app-1..3\n  migrate:   profile tools — alembic upgrade\n\n# Local without Docker:\nuvicorn main:app --host 0.0.0.0 --port 8000\n"
    },
    {
      "service": "ticket-service",
      "description": "Postgres + Mongo + Redis + three HTTP replicas + nginx.",
      "content": "# docker/docker-compose.yml (summary)\nservices:\n  db:    postgres:16  → host 5431\n  mongo: mongo:7      → host 27017\n  redis: redis:7      → host 6378\n  app-1: ticket-service:local (migrations on start)\n  app-2: ticket-service:local\n  app-3: ticket-service:local\n  nginx: ports 80/443\n  migrate: profile tools\n\n# Kafka bridge example:\n# docker-compose.kafka-bridge.example.yml\n"
    },
    {
      "service": "account-service",
      "description": "Docker Compose project name is account-service (legacy). Three HTTP replicas, gRPC sidecar, nginx, Postgres, Redis.",
      "content": "# docker/docker-compose.yml (summary)\nname: account-service\nservices:\n  db:     postgres:16  → host 5431 (cinema_account)\n  redis:  redis:7      → host 6378\n  app-1:  account-service:local (migrations + gunicorn)\n  app-2:  account-service:local\n  app-3:  account-service:local\n  app-grpc: serve-grpc → 50051\n  nginx:  ports 80/443\n  migrate: profile tools\n"
    },
    {
      "service": "wallet-service",
      "description": "Multi-stage Python 3.13 image; exposes 8000 and 50051; non-root user.",
      "content": "FROM python:3.13-slim AS builder\nWORKDIR /app\nCOPY requirements.txt .\nRUN python -m venv /opt/venv && /opt/venv/bin/pip install -r requirements.txt\n\nFROM python:3.13-slim AS runtime\nWORKDIR /app\nCOPY --from=builder /opt/venv /opt/venv\nCOPY . .\nUSER app\nEXPOSE 8000 50051\nHEALTHCHECK CMD python -c \"import urllib.request; urllib.request.urlopen('http://127.0.0.1:8000/health')\"\nCMD [\"/app/docker/docker-entrypoint.sh\", \"serve\"]\n"
    },
    {
      "service": "local-stack",
      "description": "docker-compose.yml — Postgres 16, Redis 7, 3 REST replicas, gRPC, NGINX.",
      "content": "services:\n  db:\n    image: postgres:16-alpine\n    ports: [\"5431:5432\"]\n  redis:\n    image: redis:7-alpine\n    ports: [\"6378:6379\"]\n  app-1:\n    build: { context: .., dockerfile: docker/dockerfile }\n  app-2:\n    image: wallet-service:local\n  app-3:\n    image: wallet-service:local\n  app-grpc:\n    command: [\"/app/docker/docker-entrypoint.sh\", \"serve-grpc\"]\n    ports: [\"50051:50051\"]\n  nginx:\n    ports: [\"80:80\", \"443:443\"]\n"
    },
    {
      "service": "production (EC2)",
      "description": "docker-compose.prod.yml — REST container; optional gRPC profile.",
      "content": "services:\n  app:\n    build: { context: .., dockerfile: docker/dockerfile }\n    env_file: [../.env]\n    ports: [\"${API_PORT:-8000}:8000\"]\n  app-grpc:\n    profiles: [grpc]\n    command: [\"/app/docker/docker-entrypoint.sh\", \"serve-grpc\"]\n    ports: [\"${GRPC_PORT:-50051}:${GRPC_PORT:-50051}\"]\n"
    }
  ],
  "cloudServices": [
    {
      "name": "PostgreSQL 15+",
      "purpose": "Primary database for showtimes and seat reservations (billboard schema)",
      "icon": "🗄️",
      "cost": "~$50/month (small RDS instance)"
    },
    {
      "name": "Redis 7",
      "purpose": "Caching layer for showtime queries and seat availability",
      "icon": "⚡",
      "cost": "~$25/month (small ElastiCache node)"
    },
    {
      "name": "AWS ECS / EC2",
      "purpose": "Container runtime for billboard-service replicas",
      "icon": "🐳",
      "cost": "Variable by instance size"
    },
    {
      "name": "PostgreSQL 15+",
      "purpose": "Primary store for movies, cinemas, theaters, seats (catalog schema)",
      "icon": "🗄️",
      "cost": "~$50/month (small RDS)"
    },
    {
      "name": "Redis 7",
      "purpose": "Cache layer for catalog queries",
      "icon": "⚡",
      "cost": "~$25/month (small ElastiCache)"
    },
    {
      "name": "AWS ECS / EC2",
      "purpose": "Container runtime for catalog-service replicas",
      "icon": "🐳",
      "cost": "Variable"
    },
    {
      "name": "PostgreSQL 16",
      "purpose": "Products, categories, combos, promotions (cinema_concession DB)",
      "icon": "🗄️",
      "cost": "~$50/month (small RDS)"
    },
    {
      "name": "Redis 7",
      "purpose": "Catalog read cache",
      "icon": "⚡",
      "cost": "~$25/month (ElastiCache)"
    },
    {
      "name": "Container runtime",
      "purpose": "ECS/EC2 or local Docker Compose",
      "icon": "🐳",
      "cost": "Variable"
    },
    {
      "name": "Amazon RDS (PostgreSQL 16)",
      "purpose": "Primary database for employees, schedules, and vacation_requests (employee schema)",
      "icon": "🗄️",
      "cost": "~$15–50/month (db.t3.micro – small instance)"
    },
    {
      "name": "Upstash Redis",
      "purpose": "Serverless cache layer — REDIS_URL with TLS; key prefix cinema:employee",
      "icon": "⚡",
      "cost": "Free tier / ~$10/month (usage-based)"
    },
    {
      "name": "AWS EC2",
      "purpose": "Hosts Docker container running employee-service (docker-compose.prod.yml)",
      "icon": "🐳",
      "cost": "~$10–30/month (t3.small or similar)"
    },
    {
      "name": "AWS Secrets Manager / SSM",
      "purpose": "JWT_SECRET_KEY, POSTGRES_PASSWORD — injected into EC2 .env at deploy time",
      "icon": "🔐",
      "cost": "Minimal per secret"
    },
    {
      "name": "MongoDB Atlas",
      "purpose": "Primary notification document store",
      "icon": "🗄️",
      "cost": "~$50/month (small cluster)"
    },
    {
      "name": "Redis 7",
      "purpose": "Response cache (when init_cache wired)",
      "icon": "⚡",
      "cost": "~$25/month"
    },
    {
      "name": "Managed Kafka",
      "purpose": "Event ingestion from platform services",
      "icon": "📤",
      "cost": "Variable"
    },
    {
      "name": "SendGrid / SMTP relay",
      "purpose": "Transactional email delivery",
      "icon": "📧",
      "cost": "Per message"
    },
    {
      "name": "Twilio",
      "purpose": "SMS delivery (optional)",
      "icon": "💬",
      "cost": "Per SMS"
    },
    {
      "name": "PostgreSQL 16",
      "purpose": "Primary payment and transaction store (cinema_payment)",
      "icon": "🗄️",
      "cost": "~$50/month (managed small instance)"
    },
    {
      "name": "Redis 7",
      "purpose": "Optional cache when REDIS_VALIDATE_ON_STARTUP=true",
      "icon": "⚡",
      "cost": "~$25/month"
    },
    {
      "name": "Managed Kafka",
      "purpose": "payment.events / payment.incoming / wallet / billboard topics",
      "icon": "📤",
      "cost": "Variable"
    },
    {
      "name": "Stripe",
      "purpose": "Card payments, PaymentIntents, stored payment tokens",
      "icon": "💳",
      "cost": "Per transaction"
    },
    {
      "name": "Service Registry",
      "purpose": "Optional heartbeat when REGISTRY_ENABLED=true",
      "icon": "📋",
      "cost": "Internal"
    },
    {
      "name": "PostgreSQL 16",
      "purpose": "Ticket records and seat assignments (cinema_ticket)",
      "icon": "🗄️",
      "cost": "~$50/month"
    },
    {
      "name": "MongoDB 7",
      "purpose": "Billboard read model (cinema_tickets)",
      "icon": "🍃",
      "cost": "~$50/month"
    },
    {
      "name": "Redis 7",
      "purpose": "In compose; cache not wired at startup",
      "icon": "⚡",
      "cost": "~$25/month"
    },
    {
      "name": "Managed Kafka",
      "purpose": "billboard.events, wallet.events, DLQ topics",
      "icon": "📤",
      "cost": "Variable"
    },
    {
      "name": "Service Registry",
      "purpose": "Optional REGISTRY_ENABLED heartbeat",
      "icon": "📋",
      "cost": "Internal"
    },
    {
      "name": "PostgreSQL 16",
      "purpose": "User accounts, profiles, credentials (cinema_account DB)",
      "icon": "🗄️",
      "cost": "~$50/month (managed small instance)"
    },
    {
      "name": "Redis 7",
      "purpose": "Refresh tokens and FastAPI-Cache",
      "icon": "⚡",
      "cost": "~$25/month"
    },
    {
      "name": "Managed Kafka",
      "purpose": "cinema.user-service.events outbound",
      "icon": "📤",
      "cost": "Variable"
    },
    {
      "name": "Amazon RDS (PostgreSQL 16)",
      "purpose": "cinema_wallets, wallet_transactions, users cache tables",
      "icon": "🗄️",
      "cost": "~$15–50/month (db.t3.micro – small instance)"
    },
    {
      "name": "Upstash Redis",
      "purpose": "Serverless cache — REDIS_URL with TLS; prefix cinema:wallet",
      "icon": "⚡",
      "cost": "Free tier / ~$10/month (usage-based)"
    },
    {
      "name": "AWS EC2",
      "purpose": "Docker host for wallet-service REST (+ optional gRPC profile)",
      "icon": "🐳",
      "cost": "~$10–30/month (t3.small or similar)"
    },
    {
      "name": "Apache Kafka (optional)",
      "purpose": "wallet.events topic for transaction notifications",
      "icon": "📤",
      "cost": "Variable / MSK or self-hosted placeholder"
    },
    {
      "name": "AWS Secrets Manager / SSM",
      "purpose": "JWT_SECRET_KEY, POSTGRES_PASSWORD",
      "icon": "🔐",
      "cost": "Minimal per secret"
    }
  ],
  "metrics": [
    {
      "label": "API Response Time (p95)",
      "value": "150ms",
      "icon": "⚡",
      "description": "95th percentile REST response time"
    },
    {
      "label": "Seat Reservation Time",
      "value": "50ms",
      "icon": "💺",
      "description": "Average seat take/release latency"
    },
    {
      "label": "Redis Cache Hit Rate",
      "value": "85%",
      "icon": "⚡",
      "description": "Target cache hit rate for showtime reads"
    },
    {
      "label": "Active DB Connections",
      "value": "20",
      "icon": "🗄️",
      "description": "Pooled async SQLAlchemy connections"
    },
    {
      "label": "Queries Per Second",
      "value": "5000",
      "icon": "📊",
      "description": "Peak search QPS under load"
    },
    {
      "label": "Service Uptime",
      "value": "99.9%",
      "icon": "🟢",
      "description": "Monthly availability target"
    },
    {
      "label": "Active Showtimes",
      "value": "500",
      "icon": "📅",
      "description": "Typical active/upcoming showtime count"
    },
    {
      "label": "Concurrent Reservations",
      "value": "1000+",
      "icon": "💺",
      "description": "Max concurrent seat operations"
    },
    {
      "label": "API Response Time (p95)",
      "value": "150ms",
      "icon": "⚡",
      "description": "95th percentile REST response time"
    },
    {
      "label": "gRPC Response Time",
      "value": "30ms",
      "icon": "🔗",
      "description": "Average catalog gRPC query latency"
    },
    {
      "label": "Redis Cache Hit Rate",
      "value": "85%",
      "icon": "⚡",
      "description": "Target when Redis lifespan init is enabled"
    },
    {
      "label": "Active DB Connections",
      "value": "20",
      "icon": "🗄️",
      "description": "Pooled async connections"
    },
    {
      "label": "Queries Per Second",
      "value": "10000",
      "icon": "📊",
      "description": "Peak catalog read QPS"
    },
    {
      "label": "Service Uptime",
      "value": "99.9%",
      "icon": "🟢",
      "description": "Monthly availability target"
    },
    {
      "label": "Total Movies",
      "value": "500",
      "icon": "🎬",
      "description": "Typical catalog size"
    },
    {
      "label": "Total Cinemas",
      "value": "50",
      "icon": "🏠",
      "description": "Cinema locations in catalog"
    },
    {
      "label": "API Response Time (p95)",
      "value": "100ms",
      "icon": "⚡",
      "description": "REST endpoint latency target"
    },
    {
      "label": "Database Query (p95)",
      "value": "50ms",
      "icon": "🗄️",
      "description": "PostgreSQL query latency"
    },
    {
      "label": "gRPC Response",
      "value": "30ms",
      "icon": "🔗",
      "description": "Catalog RPC average"
    },
    {
      "label": "Cache Hit Rate",
      "value": "85%",
      "icon": "⚡",
      "description": "Redis hit ratio target"
    },
    {
      "label": "Concurrent Requests",
      "value": "500+",
      "icon": "📊",
      "description": "Per Gunicorn worker"
    },
    {
      "label": "Service Uptime",
      "value": "99.9%",
      "icon": "🟢",
      "description": "Monthly availability"
    },
    {
      "label": "App Instances",
      "value": "3",
      "icon": "🐳",
      "description": "REST replicas behind NGINX"
    },
    {
      "label": "Gunicorn Workers",
      "value": "4",
      "icon": "⚙️",
      "description": "Per instance (GUNICORN_WORKERS default)"
    },
    {
      "label": "API Response Time (p95)",
      "value": "200ms",
      "icon": "⚡",
      "description": "95th percentile REST response time"
    },
    {
      "label": "Redis Cache Hit Rate",
      "value": "80%",
      "icon": "⚡",
      "description": "Target when Upstash Redis is reachable from EC2"
    },
    {
      "label": "Active DB Connections",
      "value": "20",
      "icon": "🗄️",
      "description": "Pooled async SQLAlchemy connections to RDS"
    },
    {
      "label": "Queries Per Second",
      "value": "1000",
      "icon": "📊",
      "description": "Peak employee list QPS under load"
    },
    {
      "label": "Service Uptime",
      "value": "99.9%",
      "icon": "🟢",
      "description": "Monthly availability target"
    },
    {
      "label": "App Replicas (local)",
      "value": "3",
      "icon": "🐳",
      "description": "docker-compose.local.yml runs app-1, app-2, app-3 behind NGINX"
    },
    {
      "label": "REST Endpoints",
      "value": "22",
      "icon": "🌐",
      "description": "Health + employees + schedules + vacations"
    },
    {
      "label": "DB Tables",
      "value": "3",
      "icon": "🗄️",
      "description": "employees, schedules, vacation_requests"
    },
    {
      "label": "API Response Time (p95)",
      "value": "100ms",
      "icon": "⚡",
      "description": "REST endpoint latency target"
    },
    {
      "label": "Event Processing",
      "value": "Sub-second",
      "icon": "📡",
      "description": "Kafka message handling latency"
    },
    {
      "label": "MongoDB Query",
      "value": "< 50ms",
      "icon": "🗄️",
      "description": "Indexed lookups by notification_id, user_id"
    },
    {
      "label": "Cache Hit Rate",
      "value": "90%+",
      "icon": "⚡",
      "description": "Target when Redis init enabled"
    },
    {
      "label": "Throughput",
      "value": "1000+/min",
      "icon": "📊",
      "description": "Notifications per minute"
    },
    {
      "label": "Service Uptime",
      "value": "99.9%",
      "icon": "🟢",
      "description": "Monthly availability target"
    },
    {
      "label": "Consumer Topics",
      "value": "3",
      "icon": "📤",
      "description": "Default Kafka topic subscriptions"
    },
    {
      "label": "Channels",
      "value": "4",
      "icon": "📬",
      "description": "EMAIL, SMS, PUSH, IN_APP"
    },
    {
      "label": "API Response Time (p95)",
      "value": "< 200ms",
      "icon": "⚡",
      "description": "REST endpoint latency target"
    },
    {
      "label": "Payment Success Rate",
      "value": "99.5%+",
      "icon": "💳",
      "description": "Completed vs failed payments"
    },
    {
      "label": "Transaction Throughput",
      "value": "1000 TPS",
      "icon": "📊",
      "description": "Peak transactions per second"
    },
    {
      "label": "Refund SLA",
      "value": "< 24h",
      "icon": "↩️",
      "description": "Target refund processing window"
    },
    {
      "label": "Kafka Latency",
      "value": "< 50ms",
      "icon": "📤",
      "description": "Event publish latency target"
    },
    {
      "label": "Service Uptime",
      "value": "99.9%",
      "icon": "🟢",
      "description": "Monthly availability target"
    },
    {
      "label": "App Replicas",
      "value": "3",
      "icon": "⚙️",
      "description": "HTTP workers behind nginx in compose"
    },
    {
      "label": "gRPC Port",
      "value": "50051",
      "icon": "🔗",
      "description": "Separate app-grpc container"
    },
    {
      "label": "API Response Time (p95)",
      "value": "< 200ms",
      "icon": "⚡",
      "description": "REST endpoint latency target"
    },
    {
      "label": "Purchase Throughput",
      "value": "1000/min",
      "icon": "🎫",
      "description": "Peak buy requests per minute"
    },
    {
      "label": "Seat Check Latency",
      "value": "< 50ms",
      "icon": "💺",
      "description": "Mongo replica read target"
    },
    {
      "label": "Kafka Processing",
      "value": "99.9%",
      "icon": "📤",
      "description": "Event sync success rate target"
    },
    {
      "label": "Service Uptime",
      "value": "99.95%",
      "icon": "🟢",
      "description": "Monthly availability target"
    },
    {
      "label": "HTTP Replicas",
      "value": "3",
      "icon": "⚙️",
      "description": "app-1..3 behind nginx"
    },
    {
      "label": "Data Stores",
      "value": "3",
      "icon": "🗄️",
      "description": "PostgreSQL + MongoDB + Redis (compose)"
    },
    {
      "label": "API Response Time (p95)",
      "value": "< 100ms",
      "icon": "⚡",
      "description": "REST endpoint latency target"
    },
    {
      "label": "Redis Session Lookup",
      "value": "< 10ms",
      "icon": "🔑",
      "description": "Refresh token read latency"
    },
    {
      "label": "Auth Success Rate",
      "value": "99%+",
      "icon": "🔐",
      "description": "Successful authentication ratio"
    },
    {
      "label": "Service Uptime",
      "value": "99.9%",
      "icon": "🟢",
      "description": "Monthly availability target"
    },
    {
      "label": "HTTP Replicas",
      "value": "3",
      "icon": "⚙️",
      "description": "app-1..3 behind nginx"
    },
    {
      "label": "gRPC Port",
      "value": "50051",
      "icon": "🔗",
      "description": "app-grpc container"
    },
    {
      "label": "API Response Time (p95)",
      "value": "200ms",
      "icon": "⚡",
      "description": "95th percentile REST response time"
    },
    {
      "label": "Redis Cache Hit Rate",
      "value": "80%",
      "icon": "⚡",
      "description": "Target when Upstash Redis is reachable from EC2"
    },
    {
      "label": "Active DB Connections",
      "value": "20",
      "icon": "🗄️",
      "description": "Pooled async SQLAlchemy connections to RDS"
    },
    {
      "label": "Default Rate Limit",
      "value": "30/min",
      "icon": "🚦",
      "description": "SlowAPI global default per client IP"
    },
    {
      "label": "Service Uptime",
      "value": "99.9%",
      "icon": "🟢",
      "description": "Monthly availability target"
    },
    {
      "label": "App Replicas (local)",
      "value": "3",
      "icon": "🐳",
      "description": "docker-compose.yml REST replicas behind NGINX"
    },
    {
      "label": "REST Endpoints",
      "value": "13",
      "icon": "🌐",
      "description": "Root, health, staff, customer, management"
    },
    {
      "label": "Currencies",
      "value": "3",
      "icon": "💱",
      "description": "USD, EUR, MXN"
    }
  ]
} as unknown as InfrastructureModel;
