// Auto-generated by parse-project-docs.js
import { ProjectCodeShowCase } from '../../../../../../core/models/project-docs.models';

export const codeShowcase = {
  "codeExamples": [
    {
      "id": "specification-search",
      "title": "Specification-based recipe search",
      "description": "RecipeSpecificationBuilder composes domain specifications into a single SQL query—keeps search logic out of controllers.",
      "category": "domain",
      "duration": "5 min read",
      "views": 0,
      "tags": [
        "ddd",
        "search",
        "sqlalchemy"
      ],
      "files": [
        {
          "name": "specification_builder.py",
          "path": "app/modules/recipe/infrastructure/persistence/specification_builder.py",
          "language": "python",
          "highlighted": true,
          "explanation": "Criteria DTO → AndSpecification chain → repository executes with joins.",
          "content": "class RecipeSpecificationBuilder:\n    @staticmethod\n    def build_from_criteria(criteria: RecipeSearchCriteria) -> Specification:\n        if not criteria.include_deleted:\n            spec = RecipeIsActiveSpecification()\n        else:\n            spec = None\n        if criteria.name:\n            name_spec = RecipeByNameSpecification(criteria.name)\n            spec = name_spec if spec is None else AndSpecification(spec, name_spec)\n        if criteria.author_id:\n            author_spec = RecipeByAuthorSpecification(criteria.author_id)\n            spec = author_spec if spec is None else AndSpecification(spec, author_spec)\n        return spec\n"
        }
      ]
    },
    {
      "id": "create-recipe-use-case",
      "title": "Create recipe use case",
      "description": "Application layer orchestrates validation, persistence, and DTO mapping without FastAPI imports.",
      "category": "application",
      "duration": "4 min read",
      "views": 0,
      "tags": [
        "use-case",
        "clean-architecture"
      ],
      "files": [
        {
          "name": "create_recipe.py",
          "path": "app/modules/recipe/application/use_cases/recipe/create_recipe.py",
          "language": "python",
          "highlighted": true,
          "explanation": "Injected IRecipeRepository; maps CreateRecipeRequest to domain Recipe aggregate.",
          "content": "class CreateRecipeUseCase:\n    def __init__(self, recipe_repository: IRecipeRepository):\n        self._recipe_repository = recipe_repository\n\n    async def execute(\n        self, request: CreateRecipeRequest, author_id: UserId\n    ) -> RecipeCreatedResponse:\n        # Build domain entity, validate invariants, persist\n        recipe = self._build_recipe_from_request(request, author_id)\n        saved = await self._recipe_repository.save(recipe)\n        return RecipeCreatedResponse.from_entity(saved)\n"
        }
      ]
    },
    {
      "id": "rate-limit-decorator",
      "title": "Declarative rate limits on routes",
      "description": "@rate_limit profile names map to RATE_LIMIT_CONFIG windows per client IP.",
      "category": "security",
      "duration": "3 min read",
      "views": 0,
      "tags": [
        "rate-limit",
        "fastapi"
      ],
      "files": [
        {
          "name": "rate_limiter.py",
          "path": "app/config/rate_limiter.py",
          "language": "python",
          "highlighted": true,
          "explanation": "Used as @rate_limit('strict') on signup/login and @rate_limit('public') on search.",
          "content": "def rate_limit(config_name: str):\n    def decorator(func):\n        rate_limit_manager.set_endpoint_limit(\n            f\"{func.__module__}.{func.__name__}\", config_name\n        )\n        return func\n    return decorator\n"
        },
        {
          "name": "auth_controller.py",
          "path": "app/modules/auth/presentation/auth_controller.py",
          "language": "python",
          "highlighted": false,
          "explanation": "Example: signup uses strict (10/min), refresh uses api (30/min).",
          "content": "@router.post(\"/signup\", ...)\n@rate_limit(\"strict\")\nasync def signup(...): ...\n"
        }
      ]
    },
    {
      "id": "fastapi-lifespan",
      "title": "Application lifespan (DB + Redis)",
      "description": "main.py wires async startup/shutdown for database and Redis used by auth sessions.",
      "category": "api",
      "duration": "2 min read",
      "views": 0,
      "tags": [
        "fastapi",
        "async"
      ],
      "files": [
        {
          "name": "main.py",
          "path": "main.py",
          "language": "python",
          "highlighted": true,
          "explanation": "ECS tasks rely on successful Redis connect before accepting traffic if health checks include dependency probes.",
          "content": "@asynccontextmanager\nasync def lifespan(app: FastAPI):\n    await init_db()\n    await initialize_redis()\n    yield\n    await close_redis()\n    await close_db()\n\napp = FastAPI(\n    title=\"Cooking Recipes API\",\n    version=\"1.0.0\",\n    lifespan=lifespan,\n)\n"
        }
      ]
    }
  ]
} as unknown as ProjectCodeShowCase;
