// Auto-generated by parse-project-docs.js
import { ProjectMetadata } from '../../project.factory';

export const metadata = {
  projectId: "cinema-platform",
  featured: true,
  name: "Cinema Platform",
  language: "Python",
  category: "backend",
  framework: "FastAPI",
  version: "1.0",
  repositoryUrl: "https://github.com/alexisTrejo11/cinema-plattform",
  liveDemoUrl: null,
  description: "Cinema Platform is a distributed backend for cinema operations, built as nine FastAPI microservices that share Clean Architecture, async PostgreSQL, Redis, and optional Kafka event streaming. It covers the full customer and staff journey: catalog and showtimes, ticketing, payments, digital wallets, concessions, identity, workforce management, and multi-channel notifications.\n\nServices communicate over REST and gRPC with JWT role-based access control. Local development uses Docker Compose; production targets AWS EC2 with RDS PostgreSQL and Upstash Redis.",
  techStack: [
  "Python 3.11+",
  "FastAPI",
  "SQLAlchemy 2.0 (async)",
  "PostgreSQL",
  "MongoDB",
  "Redis",
  "Alembic",
  "gRPC + Protobuf",
  "Kafka",
  "Stripe",
  "JWT",
  "SMTP",
  "Jinja2",
  "Twilio",
  "SlowAPI",
  "Gunicorn",
  "Uvicorn",
  "Docker",
  "pytest"
],
  status: "deployed",
  createdAt: new Date("2025-01-01T00:00:00.000Z"),
  updatedAt: new Date("2026-06-08T00:00:00.000Z"),
} satisfies ProjectMetadata;
