// Auto-generated by parse-project-docs.js
import { ProjectMetadata } from '../../project.factory';

export const metadata = {
  projectId: "drugstore-platform",
  featured: true,
  name: "Drugstore Platform",
  language: "Java",
  category: "backend",
  framework: "Spring Boot",
  version: "1.0",
  repositoryUrl: "https://github.com/alexisTrejo11/drugstore-platform",
  liveDemoUrl: null,
  description: "Multi-service drugstore e-commerce platform built with Java 23 and Spring Boot. Eleven bounded contexts (auth, users, catalog, cart, orders, payments, inventory, stores, addresses, employees, notifications) communicate via REST, gRPC, and message buses — backed by PostgreSQL, Redis, and observability tooling.",
  techStack: [
  "Java 23",
  "Spring Boot 3.3+",
  "Flyway",
  "PostgreSQL 15",
  "Redis 7",
  "Kafka",
  "gRPC + Protobuf",
  "JWT",
  "OAuth2",
  "SpringDoc OpenAPI",
  "Micrometer",
  "Prometheus",
  "Loki",
  "Grafana",
  "Docker",
  "Gradle",
  "Lombok"
],
  status: "deployed",
  createdAt: new Date("2025-01-01T00:00:00.000Z"),
  updatedAt: new Date("2026-06-19T00:00:00.000Z"),
} satisfies ProjectMetadata;
