// Auto-generated by parse-project-docs.js
import { ProjectMetadata } from '../../project.factory';

export const metadata = {
  projectId: "pimienta-alimentos-backend",
  featured: true,
  name: "Pimienta Alimentos Backend",
  language: "Java",
  category: "backend",
  framework: "Spring Boot 4",
  version: "1.0.0",
  repositoryUrl: "https://github.com/alexistrejo11/pimienta",
  liveDemoUrl: "https://{{PRODUCTION_HOST}}/api/v2/health",
  description: "Production Spring Boot API for Pimienta Alimentos — a real-world company operations platform used daily by employees and staff. Covers HR, payroll, inventory, CRM, contracts, tasks, and file management.",
  techStack: [
  "Java 25",
  "Spring Boot 4.0.5",
  "Spring Security + JWT",
  "Spring Data JPA + Hibernate",
  "PostgreSQL 16 (AWS RDS)",
  "Redis 7 (Upstash)",
  "Flyway",
  "springdoc-openapi 3",
  "Apache POI (XLSX)",
  "AWS SDK S3",
  "Docker / Docker Compose",
  "Maven"
],
  status: "deployed",
  createdAt: new Date("2024-01-01T00:00:00.000Z"),
  updatedAt: new Date("2026-06-08T00:00:00.000Z"),
} satisfies ProjectMetadata;
