// Auto-generated by parse-project-docs.js
import { ProjectCodeShowCase } from '../../../../../../core/models/project-docs.models';

export const codeShowcase = {
  "codeExamples": [
    {
      "id": "hexagonal-auth",
      "title": "Auth command handler (application core)",
      "description": "Login flow orchestrates user lookup, password validation, token generation, and Redis session persistence — domain stays free of GraphQL/JPA details.",
      "category": "authentication",
      "duration": "5 min read",
      "tags": [
        "hexagonal",
        "jwt",
        "redis"
      ],
      "files": [
        {
          "name": "AuthCommandHandler.java",
          "path": "src/main/java/at/backend/MarketingCompany/account/auth/core/application/AuthCommandHandler.java",
          "language": "java",
          "explanation": "Core use case — validates credentials and creates session via ports.",
          "content": "@Transactional\npublic AuthResult handleLogin(LoginCommand command) {\n  var user = userRepository.findByEmail(command.email())\n      .orElseThrow(InvalidCredentialsException::new);\n  validatePassword(command.password(), user.getHashedPassword());\n  var accessToken = tokenProvider.generateAccessToken(\n      user.getId().value(), user.getEmail().value(), user.getRoles());\n  var refreshToken = tokenProvider.generateRefreshToken(user.getId().value());\n  authSessionRepository.save(buildSession(user, refreshToken, command));\n  return AuthResult.of(accessToken, refreshToken, user);\n}\n"
        }
      ]
    },
    {
      "id": "graphql-auth-controller",
      "title": "GraphQL auth mutations",
      "description": "Input adapter exposing signUp, login, refresh, and logout with sensitive rate limits.",
      "category": "api",
      "duration": "3 min read",
      "tags": [
        "graphql",
        "spring"
      ],
      "files": [
        {
          "name": "AuthController.java",
          "path": "src/main/java/at/backend/MarketingCompany/account/auth/adapters/inbound/controller/AuthController.java",
          "language": "java",
          "explanation": "Maps GraphQL mutations to commands; captures client IP and user agent.",
          "content": "@MutationMapping\n@GraphQLRateLimit(\"sensitive\")\npublic AuthResponse login(\n    @Valid @Argument LoginInput input,\n    @ContextValue(name = \"userAgent\") String userAgent,\n    @ContextValue(name = \"clientIp\") String clientIp) {\n  LoginCommand command = input.toCommand(userAgent, clientIp);\n  AuthResult result = authService.handleLogin(command);\n  return authResponseMapper.toAuthResponse(result);\n}\n"
        }
      ]
    },
    {
      "id": "docker-host-overrides",
      "title": "Docker Compose host overrides",
      "description": "Full local stack forces postgres/redis service names so the app container never connects to localhost for data stores.",
      "category": "integration",
      "duration": "2 min read",
      "tags": [
        "docker",
        "devops"
      ],
      "files": [
        {
          "name": "compose.full.yml (excerpt)",
          "path": "docker/compose.full.yml",
          "language": "yaml",
          "explanation": "Environment block overrides .env localhost values inside the app service.",
          "content": "app:\n  environment:\n    SPRING_PROFILES_ACTIVE: docker\n    SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/${POSTGRES_DB}\n    SPRING_REDIS_HOST: redis\n    DB_HOST: postgres\n"
        }
      ]
    },
    {
      "id": "env-configuration",
      "title": "Environment-driven secrets",
      "description": "JWT, database, Redis, CORS, and Kafka settings come from .env — loaded by spring-dotenv locally and passed to EC2/Docker in production.",
      "category": "security",
      "duration": "2 min read",
      "tags": [
        "config",
        "aws"
      ],
      "files": [
        {
          "name": "application.yml (auth excerpt)",
          "path": "src/main/resources/application.yml",
          "language": "yaml",
          "explanation": "Production profile requires JWT secrets without insecure defaults.",
          "content": "app:\n  auth:\n    jwt:\n      access-secret: ${JWT_ACCESS_SECRET}\n      refresh-secret: ${JWT_REFRESH_SECRET}\n      access-expiration-minutes: ${JWT_ACCESS_EXPIRATION_MINUTES:15}\n      refresh-expiration-days: ${JWT_REFRESH_EXPIRATION_DAYS:30}\n"
        }
      ]
    },
    {
      "id": "redis-sessions",
      "title": "Redis session repository",
      "description": "Refresh tokens are session IDs; user session sets enable logout-all.",
      "category": "caching",
      "duration": "4 min read",
      "tags": [
        "redis",
        "upstash"
      ],
      "files": [
        {
          "name": "RedisAuthSessionRepositoryImpl.java (excerpt)",
          "path": "src/main/java/at/backend/MarketingCompany/account/auth/adapters/outbound/persistence/RedisAuthSessionRepositoryImpl.java",
          "language": "java",
          "explanation": "Session keys prefixed with session: and indexed per user in Redis sets.",
          "content": "private static final String SESSION_KEY_PREFIX = \"session:\";\nprivate static final String USER_SESSIONS_PREFIX = \"user_sessions:\";\n\npublic void save(AuthSession session) {\n  String refreshToken = session.getSessionId().value();\n  redisTemplate.opsForValue().set(getSessionKey(refreshToken), entity);\n  redisTemplate.opsForSet().add(getUserSessionsKey(userId), refreshToken);\n}\n"
        }
      ]
    }
  ]
} as unknown as ProjectCodeShowCase;
