// Auto-generated by parse-project-docs.js
import { ProjectCodeShowCase } from '../../../../../../core/models/project-docs.models';

export const codeShowcase = {
  "codeExamples": [
    {
      "id": "redis-key-prefix",
      "title": "Redis key prefix for shared Upstash",
      "description": "Namespaces django-redis cache keys and Celery broker/result keys so multiple services can share one Upstash instance safely.",
      "category": "infrastructure",
      "duration": "3 min read",
      "views": 0,
      "tags": [
        "redis",
        "upstash",
        "celery"
      ],
      "files": [
        {
          "name": "base.py",
          "path": "config/settings/base.py",
          "language": "python",
          "highlighted": true,
          "explanation": "REDIS_KEY_PREFIX defaults to social-events-api: and applies to cache KEY_PREFIX and Celery global_keyprefix.",
          "content": "REDIS_KEY_PREFIX = env(\"REDIS_KEY_PREFIX\")\n\ndef redis_cache_options(**extra):\n    return {\n        \"CLIENT_CLASS\": \"django_redis.client.DefaultClient\",\n        \"KEY_PREFIX\": REDIS_KEY_PREFIX,\n        **extra,\n    }\n\nCELERY_BROKER_TRANSPORT_OPTIONS = {\"global_keyprefix\": REDIS_KEY_PREFIX}\nCELERY_RESULT_BACKEND_TRANSPORT_OPTIONS = {\"global_keyprefix\": REDIS_KEY_PREFIX}\n"
        }
      ]
    },
    {
      "id": "event-permissions",
      "title": "Event role & organization manager checks",
      "description": "Permission helpers combine per-event roles (host, moderator) with organization membership for cross-event administration.",
      "category": "security",
      "duration": "4 min read",
      "views": 0,
      "tags": [
        "events",
        "permissions",
        "organizations"
      ],
      "files": [
        {
          "name": "permissions.py",
          "path": "apps/events/permissions.py",
          "language": "python",
          "highlighted": true,
          "explanation": "Org owners/admins/managers can manage events linked to their organization even if not the original organizer.",
          "content": "def has_event_role(user, event, *roles) -> bool:\n    if not user or not user.is_authenticated:\n        return False\n    event_role = get_event_role(user, event)\n    return event_role is not None and event_role.role in roles\n\ndef is_event_org_manager(user, event) -> bool:\n    if not event.organization:\n        return False\n    membership = OrganizationMembership.objects.get(\n        user=user, organization=event.organization\n    )\n    return membership.role in (\n        OrganizationMembership.Role.OWNER,\n        OrganizationMembership.Role.ADMIN,\n        OrganizationMembership.Role.MANAGER,\n    )\n"
        }
      ]
    },
    {
      "id": "rate-limit-middleware",
      "title": "Global rate limit middleware",
      "description": "IP-based limits for anonymous clients and user-id limits for authenticated users, backed by Django cache (Redis in production).",
      "category": "performance",
      "duration": "3 min read",
      "views": 0,
      "tags": [
        "throttling",
        "redis"
      ],
      "files": [
        {
          "name": "throttling.py",
          "path": "common/throttling.py",
          "language": "python",
          "highlighted": true,
          "explanation": "Fails open on Redis errors so cache outages do not hard-down the API.",
          "content": "class RateLimitMiddleware:\n    ANON_LIMIT = (200, 60)\n    AUTH_LIMIT = (1000, 60)\n    EXEMPT_PATHS = {\"/health/\", \"/api/schema/\", \"/api/docs/\"}\n\n    def __call__(self, request):\n        if request.path in self.EXEMPT_PATHS:\n            return self.get_response(request)\n        limit, window = self._get_limit(request)\n        allowed, remaining, reset_at = self._check_limit(...)\n        if not allowed:\n            return JsonResponse({\"error\": {\"code\": \"rate_limit_exceeded\", ...}}, status=429)\n"
        }
      ]
    },
    {
      "id": "audit-sanitize",
      "title": "Audit log with sensitive field redaction",
      "description": "Middleware logs request metadata and JSON bodies with passwords and tokens masked.",
      "category": "security",
      "duration": "2 min read",
      "views": 0,
      "tags": [
        "audit",
        "logging"
      ],
      "files": [
        {
          "name": "audit_log.py",
          "path": "common/audit_log.py",
          "language": "python",
          "highlighted": true,
          "explanation": "SENSITIVE_FIELDS set prevents credential leakage into log aggregators on EC2.",
          "content": "SENSITIVE_FIELDS = {\"password\", \"token\", \"access\", \"refresh\"}\n\ndef sanitize_data(data):\n    if not isinstance(data, dict):\n        return None\n    return {\n        key: (\"***\" if key.lower() in SENSITIVE_FIELDS else value)\n        for key, value in data.items()\n    }\n"
        }
      ]
    },
    {
      "id": "celery-signals",
      "title": "Celery app with task lifecycle logging",
      "description": "Celery autodiscovers tasks from apps and common; signal handlers log task start, success, failure, and retry.",
      "category": "messaging",
      "duration": "3 min read",
      "views": 0,
      "tags": [
        "celery",
        "async"
      ],
      "files": [
        {
          "name": "celery.py",
          "path": "config/celery.py",
          "language": "python",
          "highlighted": true,
          "explanation": "Worker should run on EC2 alongside web container when email notifications must be reliable.",
          "content": "app = Celery(\"social_events_api\")\napp.config_from_object(\"django.conf:settings\", namespace=\"CELERY\")\napp.autodiscover_tasks()\napp.autodiscover_tasks([\"common\"])\napp.autodiscover_tasks([\"apps\"])\n\n@task_prerun.connect\ndef task_prerun_handler(sender=None, task_id=None, task=None, **extra):\n    logger.info(f\"Task Started: {task.name} [ID: {task_id}]\")\n"
        }
      ]
    }
  ]
} as unknown as ProjectCodeShowCase;
