// Auto-generated by parse-project-docs.js
import { ProjectMetadata } from '../../project.factory';

export const metadata = {
  projectId: "mind-care-company-api",
  featured: true,
  name: "MindCare Hub API",
  language: "Python",
  category: "backend",
  framework: "Django REST Framework",
  version: "2.0.0",
  repositoryUrl: "https://github.com/your-org/mind-care-company-api",
  liveDemoUrl: "https://api.mindcarehub.example.com/api/v2/health/",
  description: "REST API for small mental-health practices: patient onboarding, specialist scheduling, confidential medical records, billing, and notifications for psychologists, psychiatrists, and therapists.",
  techStack: [
  "Django 5.1.5",
  "Django REST Framework",
  "PostgreSQL",
  "Redis (django-redis)",
  "Celery",
  "SimpleJWT",
  "Stripe",
  "drf-spectacular",
  "Docker",
  "Gunicorn"
],
  status: "deployed",
  createdAt: new Date("2025-06-01T00:00:00.000Z"),
  updatedAt: new Date("2026-05-30T00:00:00.000Z"),
} satisfies ProjectMetadata;
