// Auto-generated by parse-project-docs.js
import { ProjectCodeShowCase } from '../../../../../../core/models/project-docs.models';

export const codeShowcase = {
  "codeExamples": [
    {
      "id": "hexagonal-auth-controller",
      "title": "Thin REST adapter with use-case port",
      "description": "AuthController delegates to AuthUseCases input port — no business logic in the web layer. OpenAPI and rate limits applied declaratively.",
      "category": "Hexagonal / Web",
      "tags": [
        "auth",
        "controller",
        "rate-limit"
      ],
      "files": [
        {
          "name": "AuthController.java",
          "path": "src/main/java/.../auth/infrastructure/adapter/inbound/web/AuthController.java",
          "language": "java",
          "highlighted": true,
          "explanation": "Driving adapter: maps HTTP DTOs to commands and invokes the application port.",
          "content": "@RestController\n@RequestMapping(\"/api/v1/auth\")\npublic class AuthController {\n\n  private final AuthUseCases authUseCases;\n\n  @PostMapping(\"/login\")\n  @RateLimit(profile = RateLimitProfile.STRICT)\n  public TokenResponse login(@Valid @RequestBody LoginRequest request) {\n    LoginCommand command = AuthWebMapper.toLoginCommand(request);\n    IssuedTokens issued = authUseCases.login(command);\n    return AuthWebMapper.toResponse(issued);\n  }\n}\n"
        }
      ]
    },
    {
      "id": "security-config",
      "title": "Stateless JWT security filter chain",
      "description": "Public paths for auth, health, and Swagger; role rules for admin/manager routes; JWT filter before UsernamePasswordAuthenticationFilter.",
      "category": "Security",
      "tags": [
        "jwt",
        "spring-security"
      ],
      "files": [
        {
          "name": "SecurityConfig.java",
          "path": "src/main/java/.../config/security/SecurityConfig.java",
          "language": "java",
          "highlighted": true,
          "explanation": "Central security policy for the production API used by all staff clients.",
          "content": "http.csrf(AbstractHttpConfigurer::disable)\n    .sessionManagement(s -> s.sessionCreationPolicy(SessionCreationPolicy.STATELESS))\n    .authorizeHttpRequests(auth -> auth\n        .requestMatchers(\"/api/v1/auth/**\").permitAll()\n        .requestMatchers(\"/api/v2/health/**\").permitAll()\n        .requestMatchers(\"/api/v1/files/management/**\").hasRole(\"ADMIN\")\n        .anyRequest().authenticated())\n    .addFilterBefore(jwtAuthenticationFilter, UsernamePasswordAuthenticationFilter.class);\n"
        }
      ]
    },
    {
      "id": "base-domain",
      "title": "Shared aggregate base with audit fields",
      "description": "All domain entities extend BaseDomain for id, timestamps, soft delete (deletedAt), and optimistic locking (version).",
      "category": "Domain",
      "tags": [
        "ddd",
        "aggregate"
      ],
      "files": [
        {
          "name": "BaseDomain.java",
          "path": "src/main/java/.../shared/BaseDomain.java",
          "language": "java",
          "explanation": "Repository-style thin aggregates share persistence metadata without JPA in the domain package.",
          "content": "public abstract class BaseDomain<ID> {\n  protected ID id;\n  protected LocalDateTime createdAt;\n  protected LocalDateTime updatedAt;\n  protected LocalDateTime deletedAt;\n  protected Long version;\n}\n"
        }
      ]
    },
    {
      "id": "global-rate-limit",
      "title": "Infrastructure-wide Redis rate limiter",
      "description": "OncePerRequestFilter applies token-bucket limits per client IP on all /api/** paths except health and actuator.",
      "category": "Performance",
      "tags": [
        "redis",
        "rate-limit"
      ],
      "files": [
        {
          "name": "GlobalRateLimitFilter.java",
          "path": "src/main/java/.../config/rate_limit/GlobalRateLimitFilter.java",
          "language": "java",
          "highlighted": true,
          "explanation": "Protects the production API from abuse while staff use the system daily.",
          "content": "protected boolean shouldNotFilter(HttpServletRequest request) {\n  String path = request.getRequestURI();\n  return !path.startsWith(\"/api/\")\n      || path.startsWith(\"/api/v2/health\")\n      || path.startsWith(\"/actuator\");\n}\n\nprotected void doFilterInternal(...) {\n  String key = \"ratelimit:global:v1:ip:\" + ClientIpResolver.resolve(request);\n  RateLimitDecision d = rateLimiter.tryConsume(key, capacity, refillPerSecond);\n  if (!d.allowed()) {\n    RateLimitResponseWriter.writeTooManyRequests(response, ...);\n    return;\n  }\n  filterChain.doFilter(request, response);\n}\n"
        }
      ]
    },
    {
      "id": "paged-response",
      "title": "Consistent pagination response",
      "description": "PagedResponse record wraps Spring Data Page into items + metadata for every list endpoint.",
      "category": "API contract",
      "tags": [
        "pagination",
        "openapi"
      ],
      "files": [
        {
          "name": "PagedResponse.java",
          "path": "src/main/java/.../shared/web/PagedResponse.java",
          "language": "java",
          "content": "public record PagedResponse<T>(\n    List<T> items,\n    PageMetadata metadata) {\n\n  public static <T> PagedResponse<T> of(Page<T> page) {\n    return new PagedResponse<>(page.getContent(), PageMetadata.fromPage(page));\n  }\n}\n"
        }
      ]
    },
    {
      "id": "docker-production",
      "title": "Production multi-stage Dockerfile",
      "description": "Maven build on JDK 25, runtime on JRE 25 Alpine with non-root spring user — deployed on AWS EC2.",
      "category": "Infrastructure",
      "tags": [
        "docker",
        "aws",
        "ec2"
      ],
      "files": [
        {
          "name": "Dockerfile",
          "path": "docker/Dockerfile",
          "language": "dockerfile",
          "highlighted": true,
          "explanation": "Image built from backend/ context; SPRING_PROFILES_ACTIVE=docker in production.",
          "content": "FROM maven:3.9-eclipse-temurin-25-alpine AS build\nRUN mvn -q -B -DskipTests package\n\nFROM eclipse-temurin:25-jre-alpine AS runtime\nUSER spring:spring\nEXPOSE 8080\nENV SPRING_PROFILES_ACTIVE=docker\nENTRYPOINT [\"sh\", \"-c\", \"exec java ${JAVA_OPTS:-} -jar /app/app.jar\"]\n"
        }
      ]
    }
  ]
} as unknown as ProjectCodeShowCase;
