// Auto-generated by parse-project-docs.js
import { InfrastructureModel } from '../../../../../../core/models/project-docs.models';

export const infrastructure = {
  "deploymentLayers": [
    {
      "name": "Edge / client",
      "components": [
        {
          "name": "Company frontend",
          "icon": "browser",
          "description": "Web app used by Pimienta staff (Angular; CORS-configured origins)."
        },
        {
          "name": "Mobile / field staff",
          "icon": "mobile",
          "description": "Authenticated clients calling /api/v1/* with JWT Bearer tokens."
        }
      ],
      "color": "#3B82F6"
    },
    {
      "name": "Compute (AWS EC2)",
      "components": [
        {
          "name": "Docker container",
          "icon": "docker",
          "description": "Multi-stage image: Maven 3.9 + JDK 25 build → JRE 25 Alpine runtime."
        },
        {
          "name": "Spring Boot API",
          "icon": "spring",
          "description": "Profile docker; port 8080; Flyway + JPA validate on startup."
        }
      ],
      "color": "#10B981"
    },
    {
      "name": "Data layer",
      "components": [
        {
          "name": "RDS PostgreSQL",
          "icon": "postgres",
          "description": "POSTGRES_URL via SPRING_DATASOURCE_* env vars in cloud compose."
        },
        {
          "name": "Upstash Redis",
          "icon": "redis",
          "description": "REDIS_URL=rediss://... for TLS; PIMIENTA_REDIS_KEY_PREFIX namespaces keys."
        },
        {
          "name": "S3 bucket",
          "icon": "s3",
          "description": "AWS_S3_BUCKET_NAME, AWS_S3_FOLDER, AWS_S3_SOURCES_ROOT."
        }
      ],
      "color": "#8B5CF6"
    }
  ],
  "dockerFiles": [
    {
      "service": "Production Dockerfile",
      "description": "Multi-stage build from backend project root; non-root user; exposes 8080.",
      "content": "FROM maven:3.9-eclipse-temurin-25-alpine AS build\nWORKDIR /workspace\nCOPY pom.xml .\nCOPY src ./src\nRUN mvn -q -B -DskipTests package\n\nFROM eclipse-temurin:25-jre-alpine AS runtime\nWORKDIR /app\nRUN addgroup -S spring -g 1001 && adduser -S spring -u 1001 -G spring\nCOPY --from=build /workspace/target/*.jar /app/app.jar\nRUN mkdir -p /app/logs && chown -R spring:spring /app\nUSER spring:spring\nEXPOSE 8080\nENV SPRING_PROFILES_ACTIVE=docker\nENTRYPOINT [\"sh\", \"-c\", \"exec java ${JAVA_OPTS:-} -jar /app/app.jar\"]\n"
    },
    {
      "service": "Cloud compose (API only)",
      "description": "Connects to external RDS and Upstash Redis via .env — used in production on EC2.",
      "content": "name: pimienta-backend\nservices:\n  api:\n    build:\n      context: ..\n      dockerfile: docker/Dockerfile\n    ports:\n      - \"${API_PORT:-8080}:8080\"\n    environment:\n      SPRING_PROFILES_ACTIVE: docker\n      SPRING_DATASOURCE_URL: ${POSTGRES_URL}\n      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}\n      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}\n      REDIS_URL: ${REDIS_URL}\n      PIMIENTA_SECURITY_JWT_SECRET: ${PIMIENTA_SECURITY_JWT_SECRET}\n      AWS_REGION: ${AWS_REGION:-us-east-1}\n      AWS_S3_BUCKET_NAME: ${AWS_S3_BUCKET_NAME}\n"
    }
  ],
  "cloudServices": [
    {
      "name": "AWS EC2",
      "purpose": "Hosts the Spring Boot API Docker container in production",
      "icon": "ec2",
      "cost": "Varies by instance type"
    },
    {
      "name": "AWS RDS (PostgreSQL 16)",
      "purpose": "Primary relational database for all domain data",
      "icon": "rds",
      "cost": "Varies by instance / storage"
    },
    {
      "name": "Upstash Redis",
      "purpose": "Refresh token store, global and per-endpoint rate limiting (token bucket Lua script)",
      "icon": "redis",
      "cost": "Pay-per-request / tiered"
    },
    {
      "name": "AWS S3",
      "purpose": "Employee photos, file assets, presigned downloads",
      "icon": "s3",
      "cost": "Storage + requests"
    },
    {
      "name": "AWS IAM",
      "purpose": "EC2 instance or access keys for S3 SDK",
      "icon": "iam",
      "cost": "Included"
    }
  ],
  "metrics": [
    {
      "label": "Runtime",
      "value": "AWS EC2",
      "icon": "server",
      "description": "Spring Boot API runs as a Docker container on an EC2 instance (profile docker)."
    },
    {
      "label": "Database",
      "value": "AWS RDS PostgreSQL 16",
      "icon": "database",
      "description": "Managed Postgres; Flyway migrations on startup; schema pimienta."
    },
    {
      "label": "Cache / sessions",
      "value": "Upstash Redis",
      "icon": "redis",
      "description": "TLS via rediss:// URL; refresh tokens, rate limiting, key prefix pimienta-alimentos."
    },
    {
      "label": "Object storage",
      "value": "AWS S3",
      "icon": "cloud",
      "description": "Employee photos and file assets; presigned URLs; region us-east-1."
    },
    {
      "label": "Container port",
      "value": "8080",
      "icon": "network",
      "description": "Exposed via API_PORT; non-root spring user inside Alpine JRE 25 image."
    }
  ]
} as unknown as InfrastructureModel;
