// Auto-generated by parse-project-docs.js
import { InfrastructureModel } from '../../../../../../core/models/project-docs.models';

export const infrastructure = {
  "deploymentLayers": [
    {
      "name": "Platform plane",
      "color": "#eceff4",
      "components": [
        {
          "name": "Spring Cloud Config",
          "icon": "settings",
          "description": "Serves config-data on port 8888."
        },
        {
          "name": "Netflix Eureka",
          "icon": "radar",
          "description": "Registry on port 8761."
        },
        {
          "name": "Spring Boot Admin",
          "icon": "monitor",
          "description": "Aggregates actuator endpoints on port 8081."
        }
      ]
    },
    {
      "name": "Data plane",
      "color": "#d8dee9",
      "components": [
        {
          "name": "PostgreSQL",
          "icon": "database",
          "description": "Host database account_db for this service."
        },
        {
          "name": "Future MongoDB / RabbitMQ",
          "icon": "n/a",
          "description": "Not used by account-service; other platform services may use them."
        }
      ]
    },
    {
      "name": "Account Service runtime",
      "color": "#88c0d0",
      "components": [
        {
          "name": "Spring Boot container",
          "icon": "coffee",
          "description": "Listens on 8082 in the default Compose file."
        },
        {
          "name": "Actuator",
          "icon": "activity",
          "description": "Health and metrics; restrict in production."
        }
      ]
    },
    {
      "name": "Platform plane",
      "color": "#eceff4",
      "components": [
        {
          "name": "Spring Cloud Config",
          "icon": "settings",
          "description": "Port 8888; config-data volume mount."
        },
        {
          "name": "Netflix Eureka",
          "icon": "radar",
          "description": "Registry 8761."
        },
        {
          "name": "Spring Boot Admin",
          "icon": "monitor",
          "description": "Aggregates actuator on 8081."
        }
      ]
    },
    {
      "name": "Data plane (this service)",
      "color": "#d8dee9",
      "components": [
        {
          "name": "PostgreSQL",
          "icon": "database",
          "description": "Database curriculum_db for all catalog entities."
        },
        {
          "name": "MongoDB / RabbitMQ",
          "icon": "n/a",
          "description": "Not used by curriculum-service; other platform services may consume them."
        }
      ]
    },
    {
      "name": "Curriculum Service runtime",
      "color": "#88c0d0",
      "components": [
        {
          "name": "Spring Boot container",
          "icon": "coffee",
          "description": "Listens on 8085 in default Compose."
        },
        {
          "name": "Actuator",
          "icon": "activity",
          "description": "Health and metrics; narrow exposure in production."
        }
      ]
    },
    {
      "name": "Platform plane",
      "color": "#eceff4",
      "components": [
        {
          "name": "Spring Cloud Config",
          "icon": "settings",
          "description": "8888; serves config-data/enrollment-service.yml."
        },
        {
          "name": "Netflix Eureka",
          "icon": "radar",
          "description": "8761."
        },
        {
          "name": "Spring Boot Admin",
          "icon": "monitor",
          "description": "8081."
        }
      ]
    },
    {
      "name": "Data plane",
      "color": "#d8dee9",
      "components": [
        {
          "name": "PostgreSQL",
          "icon": "database",
          "description": "enrollment_db — transactional enrollments."
        },
        {
          "name": "MongoDB",
          "icon": "leaf",
          "description": "Document DB (e.g. enrollment_db on cluster) for preload/status."
        }
      ]
    },
    {
      "name": "Enrollment Service runtime",
      "color": "#88c0d0",
      "components": [
        {
          "name": "Spring Boot",
          "icon": "coffee",
          "description": "Port 8087 in default Compose."
        },
        {
          "name": "Actuator",
          "icon": "activity",
          "description": "Narrow endpoint exposure in production."
        }
      ]
    },
    {
      "name": "Platform plane",
      "color": "#eceff4",
      "components": [
        {
          "name": "Spring Cloud Config",
          "icon": "settings",
          "description": "8888; config-data/schedule-service.yml."
        },
        {
          "name": "Netflix Eureka",
          "icon": "radar",
          "description": "8761."
        },
        {
          "name": "Spring Boot Admin",
          "icon": "monitor",
          "description": "8081."
        }
      ]
    },
    {
      "name": "Data & messaging",
      "color": "#d8dee9",
      "components": [
        {
          "name": "PostgreSQL",
          "icon": "database",
          "description": "schedule_db — groups, slots, assignments."
        },
        {
          "name": "RabbitMQ",
          "icon": "rabbit",
          "description": "AMQP5672; management UI 15672 in Compose."
        }
      ]
    },
    {
      "name": "Schedule Service runtime",
      "color": "#88c0d0",
      "components": [
        {
          "name": "Spring Boot",
          "icon": "coffee",
          "description": "Port 8086 host mapping by default."
        },
        {
          "name": "Actuator",
          "icon": "activity",
          "description": "Tighten exposure in production."
        }
      ]
    },
    {
      "name": "Platform plane",
      "color": "#eceff4",
      "components": [
        {
          "name": "Spring Cloud Config",
          "icon": "settings",
          "description": "8888; config-data/student-service.yml."
        },
        {
          "name": "Netflix Eureka",
          "icon": "radar",
          "description": "8761."
        },
        {
          "name": "Spring Boot Admin",
          "icon": "monitor",
          "description": "8081."
        }
      ]
    },
    {
      "name": "Data & messaging",
      "color": "#d8dee9",
      "components": [
        {
          "name": "PostgreSQL",
          "icon": "database",
          "description": "student_db."
        },
        {
          "name": "RabbitMQ",
          "icon": "rabbit",
          "description": "AMQP; Compose defaults guest unless overridden."
        }
      ]
    },
    {
      "name": "Student Service runtime",
      "color": "#88c0d0",
      "components": [
        {
          "name": "Spring Boot",
          "icon": "coffee",
          "description": "Port 8083 default."
        },
        {
          "name": "Actuator",
          "icon": "activity",
          "description": "Tighten in production."
        }
      ]
    },
    {
      "name": "Platform plane",
      "color": "#eceff4",
      "components": [
        {
          "name": "Spring Cloud Config",
          "icon": "settings",
          "description": "8888; config-data/teacher-service.yml + jwt.secret.key."
        },
        {
          "name": "Netflix Eureka",
          "icon": "radar",
          "description": "8761."
        },
        {
          "name": "Spring Boot Admin",
          "icon": "monitor",
          "description": "8081."
        }
      ]
    },
    {
      "name": "Data & messaging",
      "color": "#d8dee9",
      "components": [
        {
          "name": "PostgreSQL",
          "icon": "database",
          "description": "teacher_db."
        },
        {
          "name": "RabbitMQ",
          "icon": "rabbit",
          "description": "AMQP broker."
        }
      ]
    },
    {
      "name": "Teacher Service runtime",
      "color": "#88c0d0",
      "components": [
        {
          "name": "Spring Boot",
          "icon": "coffee",
          "description": "Port 8084 default."
        },
        {
          "name": "Actuator",
          "icon": "activity",
          "description": "Restrict in production."
        }
      ]
    }
  ],
  "dockerFiles": [
    {
      "service": "account-service (multi-stage)",
      "description": "Root Dockerfile; build arg SERVICE_NAME selects the Gradle module.",
      "content": "See repository Dockerfile — produces an executable JAR."
    },
    {
      "service": "curriculum-service (multi-stage)",
      "description": "Root Dockerfile; SERVICE_NAME selects Gradle module.",
      "content": "Produces runnable JAR; see repository Dockerfile."
    },
    {
      "service": "enrollment-service (multi-stage)",
      "description": "Root Dockerfile; SERVICE_NAME selects Gradle module.",
      "content": "Runnable JAR; see repository Dockerfile."
    },
    {
      "service": "schedule-service (multi-stage)",
      "description": "Root Dockerfile with SERVICE_NAME build arg.",
      "content": "Fat JAR; see repository Dockerfile."
    },
    {
      "service": "student-service (multi-stage)",
      "description": "Root Dockerfile; SERVICE_NAME selects module.",
      "content": "Fat JAR; see repository Dockerfile."
    },
    {
      "service": "teacher-service (multi-stage)",
      "description": "Root Dockerfile; SERVICE_NAME selects module.",
      "content": "Fat JAR; see repository Dockerfile."
    }
  ],
  "cloudServices": [
    {
      "name": "Container runtime",
      "purpose": "Runs the Spring Boot image built from the monorepo Dockerfile (SERVICE_NAME=account-service).",
      "icon": "docker",
      "cost": "Environment-specific"
    },
    {
      "name": "Container runtime",
      "purpose": "Spring Boot image from monorepo Dockerfile with SERVICE_NAME=curriculum-service.",
      "icon": "docker",
      "cost": "Environment-specific"
    },
    {
      "name": "Container runtime",
      "purpose": "Spring Boot image with SERVICE_NAME=enrollment-service.",
      "icon": "docker",
      "cost": "Environment-specific"
    },
    {
      "name": "Container runtime",
      "purpose": "Spring Boot image with SERVICE_NAME=schedule-service.",
      "icon": "docker",
      "cost": "Environment-specific"
    },
    {
      "name": "Container runtime",
      "purpose": "Spring Boot image with SERVICE_NAME=student-service.",
      "icon": "docker",
      "cost": "Environment-specific"
    },
    {
      "name": "Container runtime",
      "purpose": "Spring Boot image SERVICE_NAME=teacher-service.",
      "icon": "docker",
      "cost": "Environment-specific"
    }
  ],
  "metrics": [
    {
      "label": "Compose service key",
      "value": "account-service",
      "icon": "ship",
      "description": "Defined in root docker-compose.yml; depends on postgres, config-server, eureka-server."
    },
    {
      "label": "Compose service key",
      "value": "curriculum-service",
      "icon": "ship",
      "description": "Root docker-compose.yml: depends on postgres, config-server, eureka-server."
    },
    {
      "label": "Compose service key",
      "value": "enrollment-service",
      "icon": "ship",
      "description": "docker-compose: postgres, mongodb, config-server, eureka-server (no RabbitMQ for this module by default)."
    },
    {
      "label": "Compose service key",
      "value": "schedule-service",
      "icon": "ship",
      "description": "docker-compose: postgres, rabbitmq, config-server, eureka-server."
    },
    {
      "label": "Compose service key",
      "value": "student-service",
      "icon": "ship",
      "description": "docker-compose: postgres, rabbitmq, config-server, eureka-server."
    },
    {
      "label": "Compose service key",
      "value": "teacher-service",
      "icon": "ship",
      "description": "docker-compose: postgres, rabbitmq, config-server, eureka-server; JWT env from Compose."
    }
  ]
} as unknown as InfrastructureModel;
