// Auto-generated by parse-project-docs.js
import { ProjectMetadata } from '../../project.factory';

export const metadata = {
  projectId: "restaurant-management-api",
  featured: true,
  name: "Restaurant Management API",
  language: "Python",
  category: "backend",
  framework: "Django REST Framework",
  version: "1.0.0",
  repositoryUrl: "https://github.com/alexisTrejo11/restaurant-managemenet-api",
  liveDemoUrl: "https://{{YOUR_DEPLOYED_HOST}}/api/docs/",
  description: "Production REST API for restaurant operations — JWT auth, menu and stock, table seating, orders, payments with 16% VAT, and reservations. Deployed with AWS RDS PostgreSQL and Upstash Redis (via REDIS_URL).",
  techStack: [
  "Django 5.1.2",
  "Django REST Framework",
  "PostgreSQL (AWS RDS)",
  "Upstash Redis (django-redis)",
  "SimpleJWT",
  "drf-spectacular",
  "django-filter",
  "django-ratelimit",
  "Docker",
  "python-dotenv"
],
  status: "deployed",
  createdAt: new Date("2024-01-01T00:00:00.000Z"),
  updatedAt: new Date("2026-06-05T00:00:00.000Z"),
} satisfies ProjectMetadata;
