// Auto-generated by parse-project-docs.js
import { ProjectMetadata } from '../../project.factory';

export const metadata = {
  projectId: "veterinary-clinic-api",
  featured: true,
  name: "Veterinary Clinic API",
  language: "Go",
  category: "backend",
  framework: "Gin",
  version: "2.0.0",
  repositoryUrl: "https://github.com/alexisTrejo11/veterinary-clinic-api",
  liveDemoUrl: "https://api.vet-clinic.example.com/health",
  description: "REST API for veterinary clinic operations—customer and pet onboarding, staff scheduling, clinical sessions (vaccinations, prescriptions, surgeries), payments, and multi-channel notifications. Built with hexagonal architecture, PostgreSQL (sqlc), and Redis-backed JWT sessions.",
  techStack: [
  "Go 1.24",
  "Gin 1.10",
  "PostgreSQL 12+ (pgx / sqlc)",
  "Redis (go-redis) — JWT sessions & token revocation",
  "golang-migrate",
  "Swagger (swaggo)",
  "Twilio SMS",
  "SMTP email",
  "Docker multi-stage (Alpine)",
  "AWS RDS PostgreSQL (production)",
  "Upstash Redis (production)"
],
  status: "deployed",
  createdAt: new Date("2025-01-15T00:00:00.000Z"),
  updatedAt: new Date("2026-06-01T00:00:00.000Z"),
} satisfies ProjectMetadata;
