// Auto-generated by parse-project-docs.js
import { ProjectArchitectureModel } from '../../../../../../core/models/project-docs.models';

export const architecture = {
  "layers": [
    {
      "name": "Presentation (clients)",
      "description": "POS terminals, admin dashboards, and mobile clients consuming the REST API.",
      "color": "#6366F1",
      "expanded": true,
      "components": [
        "Staff order management UI",
        "Public menu browsing",
        "Reservation booking form"
      ],
      "responsibilities": [
        "Send JWT Bearer token on protected routes",
        "Handle standardized ApiResponse JSON envelope"
      ],
      "technologies": [
        "HTTPS",
        "REST JSON",
        "OpenAPI client (optional)"
      ]
    },
    {
      "name": "API layer",
      "description": "Django 5.1 + DRF monolith exposing /api/v1/ with ViewSets, custom actions, and function-based views.",
      "color": "#F59E0B",
      "expanded": true,
      "components": [
        "config.urls — routing",
        "apps/authorization — auth",
        "apps/users — user admin",
        "apps/menu — dishes",
        "apps/tables — seating",
        "apps/orders — order lifecycle",
        "apps/payments — billing",
        "apps/reservations — bookings",
        "apps/stock — inventory",
        "apps/shared — cross-cutting utilities"
      ],
      "responsibilities": [
        "Business rules in service classes, not views",
        "Unified exception handling and JSON responses",
        "OpenAPI schema generation"
      ],
      "technologies": [
        "Django REST Framework",
        "drf-spectacular",
        "django-filter"
      ]
    },
    {
      "name": "Data & cache",
      "description": "Persistent storage on AWS RDS PostgreSQL and hot-path cache on Upstash Redis.",
      "color": "#10B981",
      "expanded": true,
      "components": [
        "PostgreSQL — AWS RDS (DJANGO_DB_* env vars)",
        "Upstash Redis — django-redis via REDIS_URL (DB index 1)"
      ],
      "responsibilities": [
        "Transactional order/table state in PostgreSQL",
        "Menu category cache and rate-limit counters in Redis"
      ],
      "technologies": [
        "psycopg2-binary",
        "django-redis"
      ]
    },
    {
      "name": "Deployment",
      "description": "Docker container running Django runserver (dev) or Gunicorn (production placeholder).",
      "color": "#EF4444",
      "expanded": false,
      "components": [
        "dockerfile — Python 3.12-slim",
        "docker-compose.yml — local stack"
      ],
      "responsibilities": [
        "Env-injected secrets (SECRET_KEY, JWT_SECRET_KEY, DB, REDIS)",
        "Volume mount for live code reload in dev"
      ],
      "technologies": [
        "Docker",
        "Docker Compose"
      ]
    }
  ],
  "designPatterns": [
    {
      "title": "Service layer",
      "emoji": "⚙️",
      "description": "Domain logic encapsulated in *Service classes (OrderService, PaymentService, DishService, etc.) called from views.",
      "category": "Structural",
      "badge": "Core"
    },
    {
      "title": "Result type",
      "emoji": "✅",
      "description": "Auth flows use Result success/failure objects instead of raising exceptions for expected failures.",
      "category": "Behavioral",
      "badge": "Auth"
    },
    {
      "title": "Repository via ORM",
      "emoji": "🗄️",
      "description": "Django ORM models with ViewSets for CRUD; custom @action methods for domain transitions (complete, cancel).",
      "category": "Data access",
      "badge": "DRF"
    },
    {
      "title": "Unified API response",
      "emoji": "📦",
      "description": "All responses wrapped in success/message/data/timestamp envelope via shared serializers.",
      "category": "API design",
      "badge": "Shared"
    }
  ],
  "scalabilityStrategies": [
    {
      "title": "Redis for hot paths",
      "description": "Offload menu category cache to Upstash Redis to reduce DB reads on public menu endpoints."
    },
    {
      "title": "Stateless JWT auth",
      "description": "Horizontal scaling of API containers without server-side session storage."
    },
    {
      "title": "External managed DB",
      "description": "AWS RDS handles connection pooling and backups independently of the API container."
    }
  ],
  "securityStrategies": [
    {
      "title": "JWT Bearer authentication",
      "description": "HS256-signed tokens with 8-hour access lifetime; refresh token blacklist on logout."
    },
    {
      "title": "DRF throttling",
      "description": "Global AnonRateThrottle and UserRateThrottle at 40 requests/minute."
    },
    {
      "title": "Admin isolation",
      "description": "User and table mutations require Django IsAdminUser (is_staff flag)."
    },
    {
      "title": "Custom JSON exception middleware",
      "description": "JSONExceptionMiddleware ensures unhandled errors return JSON, not HTML stack traces."
    }
  ],
  "cacheStrategies": [
    {
      "name": "Default Django cache",
      "description": "django-redis backend pointing to Upstash Redis DB 1 via REDIS_URL",
      "ttl": "600s default (CACHES TIMEOUT)",
      "coverage": "Global cache backend"
    },
    {
      "name": "Menu categories",
      "description": "Key menu_categories set by DishService.list_all_categories()",
      "ttl": "86400s (24 hours)",
      "coverage": "GET /api/v1/menu/dish/categories/"
    },
    {
      "name": "Dish detail HTTP cache",
      "description": "cache_page(60*15) on DishViewSet.retrieve",
      "ttl": "900s (15 minutes)",
      "coverage": "GET /api/v1/menu/{id}/"
    },
    {
      "name": "Test fallback",
      "description": "LocMemCache when TESTING=True or running manage.py test",
      "ttl": "N/A",
      "coverage": "CI and unit test runs"
    }
  ],
  "architectureFeatures": [
    {
      "title": "Atomic table locking",
      "emoji": "🔒",
      "description": "Order creation and completion use database transactions to keep table availability consistent."
    },
    {
      "title": "Order-to-payment pipeline",
      "emoji": "💳",
      "description": "Completing an order automatically creates a pending payment with calculated VAT."
    },
    {
      "title": "OpenAPI-first docs",
      "emoji": "📖",
      "description": "drf-spectacular generates live schema consumed by Swagger UI and ReDoc."
    }
  ],
  "architectureDiagram": {
    "legendItems": [
      {
        "type": "client",
        "label": "Client apps",
        "color": "#6366F1",
        "icon": "monitor"
      },
      {
        "type": "service",
        "label": "Django API",
        "color": "#F59E0B",
        "icon": "server"
      },
      {
        "type": "database",
        "label": "AWS RDS PostgreSQL",
        "color": "#10B981",
        "icon": "database"
      },
      {
        "type": "queue",
        "label": "Upstash Redis",
        "color": "#DC382D",
        "icon": "redis"
      }
    ],
    "nodes": [
      {
        "id": "client",
        "label": "POS / Admin / Mobile",
        "type": "client",
        "x": 0,
        "y": 0,
        "status": "healthy"
      },
      {
        "id": "api",
        "label": "Restaurant API (Docker)",
        "type": "service",
        "x": 200,
        "y": 0,
        "status": "healthy"
      },
      {
        "id": "rds",
        "label": "AWS RDS PostgreSQL",
        "type": "database",
        "x": 400,
        "y": -50,
        "status": "healthy"
      },
      {
        "id": "redis",
        "label": "Upstash Redis",
        "type": "queue",
        "x": 400,
        "y": 50,
        "status": "healthy"
      }
    ],
    "connections": [
      {
        "id": "c1",
        "from": "client",
        "to": "api",
        "label": "REST /api/v1/",
        "protocol": "HTTPS JSON",
        "isActive": true
      },
      {
        "id": "c2",
        "from": "api",
        "to": "rds",
        "label": "ORM queries",
        "protocol": "PostgreSQL",
        "isActive": true
      },
      {
        "id": "c3",
        "from": "api",
        "to": "redis",
        "label": "Cache / limits",
        "protocol": "Redis",
        "isActive": true
      }
    ]
  },
  "dataFlow": {
    "requestFlow": [
      {
        "number": 1,
        "title": "Client sends request",
        "description": "HTTP request to /api/v1/ with optional Authorization Bearer JWT header.",
        "icon": "send"
      },
      {
        "number": 2,
        "title": "Middleware pipeline",
        "description": "JSONExceptionMiddleware, RatelimitMiddleware, auth, and DRF throttling process the request.",
        "icon": "filter"
      },
      {
        "number": 3,
        "title": "View or ViewSet",
        "description": "Permission check, serializer validation, then service layer execution.",
        "icon": "code"
      },
      {
        "number": 4,
        "title": "Data layer",
        "description": "PostgreSQL writes for domain state; Redis reads/writes for cache keys.",
        "icon": "database"
      },
      {
        "number": 5,
        "title": "Standardized response",
        "description": "ApiResponse JSON envelope returned with success, message, data, and timestamp.",
        "icon": "reply"
      }
    ],
    "eventFlow": [
      {
        "number": 1,
        "title": "Order completed",
        "description": "OrderService.complete_order frees table inside atomic transaction.",
        "icon": "check"
      },
      {
        "number": 2,
        "title": "Payment auto-created",
        "description": "PaymentService.create_payment_from_order generates line items and 16% VAT totals.",
        "icon": "credit-card"
      },
      {
        "number": 3,
        "title": "Reservation status change",
        "description": "Staff PATCH updates reservation status; table assignment validated by ReservationService.",
        "icon": "calendar"
      }
    ]
  },
  "techDecisions": {
    "decisions": []
  }
} as unknown as ProjectArchitectureModel;
