// Auto-generated by parse-project-docs.js
import { InfrastructureModel } from '../../../../../../core/models/project-docs.models';

export const infrastructure = {
  "deploymentLayers": [
    {
      "name": "Local development (docker-compose)",
      "color": "#3B82F6",
      "components": [
        {
          "name": "db",
          "icon": "postgres",
          "description": "postgres:latest — POSTGRES_USER/PASSWORD/DB=mydb, volume postgres_data"
        },
        {
          "name": "redis",
          "icon": "redis",
          "description": "redis:alpine — local cache at redis://redis:6379/1"
        },
        {
          "name": "restaurant_app",
          "icon": "python",
          "description": "Built from dockerfile — mounts source, runs runserver on port 8000"
        }
      ]
    },
    {
      "name": "Production (deployed)",
      "color": "#10B981",
      "components": [
        {
          "name": "API container",
          "icon": "docker",
          "description": "Django API image with SECRET_KEY, JWT_SECRET_KEY, DJANGO_DB_*, REDIS_URL from environment"
        },
        {
          "name": "AWS RDS",
          "icon": "aws-rds",
          "description": "External PostgreSQL — not containerized in production"
        },
        {
          "name": "Upstash Redis",
          "icon": "redis",
          "description": "External Redis URL — not containerized in production"
        }
      ]
    }
  ],
  "dockerFiles": [
    {
      "service": "dockerfile",
      "description": "Production-ready API image — Python 3.12-slim, libpq-dev, installs requirements.txt, exposes 8000.",
      "content": "FROM python:3.12-slim\nWORKDIR /restaurant_management_backend\nRUN apt-get update && apt-get install -y libpq-dev gcc\nCOPY requirements.txt /restaurant_management_backend/\nRUN pip install --no-cache-dir -r requirements.txt\nCOPY . /restaurant_management_backend/\nEXPOSE 8000\nCMD [\"python3\", \"manage.py\", \"runserver\", \"0.0.0.0:8000\"]\n"
    },
    {
      "service": "docker-compose.yml",
      "description": "Three-service local stack — db, redis, restaurant_app on app_network.",
      "content": "services:\n  db:\n    image: postgres:latest\n    ports: [\"5431:5432\"]\n  redis:\n    image: redis:alpine\n    ports: [\"6379:6379\"]\n  restaurant_app:\n    build: .\n    ports: [\"8000:8000\"]\n    depends_on: [db, redis]\n    environment:\n      - REDIS_URL=redis://redis:6379/1\n      - DJANGO_DB_HOST=db\n      - DJANGO_DB_NAME=mydb\n      - DJANGO_DB_USER=postgres\n      - DJANGO_DB_PASSWORD=postgres\n"
    }
  ],
  "cloudServices": [
    {
      "name": "Amazon RDS (PostgreSQL)",
      "purpose": "Production primary database — users, orders, payments, reservations, stock, menu. Connected via DJANGO_DB_NAME, DJANGO_DB_USER, DJANGO_DB_PASSWORD, DJANGO_DB_HOST, DJANGO_DB_PORT.",
      "icon": "aws-rds",
      "cost": "Varies by instance (db.t4g.micro ~$15–25/mo placeholder)"
    },
    {
      "name": "Upstash Redis",
      "purpose": "Production cache backend via REDIS_URL (django-redis, DB index 1). Menu categories, rate-limit counters, and general Django cache.",
      "icon": "redis",
      "cost": "Free tier / pay-as-you-go (~$0–10/mo placeholder)"
    },
    {
      "name": "Docker host",
      "purpose": "Runs restaurant_app container with env-injected secrets. Local dev via docker-compose; production host {{YOUR_DEPLOY_HOST}}.",
      "icon": "docker",
      "cost": "~$5–40/mo depending on provider"
    }
  ],
  "metrics": [
    {
      "label": "Container port",
      "value": "8000",
      "icon": "server",
      "description": "Django runserver binds 0.0.0.0:8000 inside restaurant_app container"
    },
    {
      "label": "Local Postgres port",
      "value": "5431:5432",
      "icon": "database",
      "description": "docker-compose maps host 5431 to container 5432 for local dev"
    },
    {
      "label": "Local Redis port",
      "value": "6379:6379",
      "icon": "redis",
      "description": "docker-compose Redis service; production uses Upstash URL instead"
    },
    {
      "label": "Python version",
      "value": "3.12",
      "icon": "code",
      "description": "python:3.12-slim base image in dockerfile"
    },
    {
      "label": "DRF throttle rate",
      "value": "40/min",
      "icon": "shield",
      "description": "AnonRateThrottle and UserRateThrottle global defaults"
    }
  ]
} as unknown as InfrastructureModel;
