// Auto-generated by parse-project-docs.js
import { ProjectOverview } from '../../../../../../core/models/project-docs.models';

export const overview = {
  "problemStatement": {
    "problemTitle": "Disconnected restaurant operations",
    "problemDescription": "Small and mid-size restaurants often track menus, table availability, orders, inventory, and payments in separate tools or spreadsheets. That leads to double-booked tables, stock overselling, inconsistent billing, and no single API for a POS or admin dashboard.",
    "problemList": [
      "Tables marked free while an active order is in progress",
      "Menu changes not reflected consistently across ordering channels",
      "Manual VAT and payment totals prone to error",
      "Stock depletion discovered only after orders are placed",
      "Reservation requests handled outside the order/table system"
    ]
  },
  "solution": {
    "solutionTitle": "One API for front-of-house and back-of-house",
    "solutionList": [
      {
        "title": "JWT-authenticated staff workflows",
        "description": "Signup, login, logout, and logout-all via SimpleJWT with standardized JSON responses and 8-hour access tokens."
      },
      {
        "title": "Table-aware ordering",
        "description": "Starting an order atomically marks the table unavailable; completing or cancelling releases it."
      },
      {
        "title": "Menu with cache-backed categories",
        "description": "Public dish browsing with Upstash Redis-cached category lists and 15-minute HTTP cache on dish detail."
      },
      {
        "title": "Payments aligned to orders",
        "description": "Payment records auto-created on order completion with 16% VAT via PaymentCalculatorService."
      },
      {
        "title": "Reservations with auto table assignment",
        "description": "Customer reservation requests validate date, party size (max 8), and assign a suitable table when possible."
      },
      {
        "title": "Deployed cloud stack",
        "description": "Dockerized Django API connected to AWS RDS PostgreSQL and Upstash Redis for production cache."
      }
    ]
  },
  "keyMetrics": {
    "metricsTitle": "Platform snapshot",
    "metricsList": [
      "9 Django domain apps (tables, users, menu, orders, payments, stock, reservations, authorization, shared)",
      "REST API v1 under /api/v1/",
      "OpenAPI at /api/docs/, /api/schema/, /api/redoc/",
      "Docker image Python 3.12 slim; docker-compose for local dev",
      "DRF throttling 40/minute for anon and authenticated users",
      "Redis cache timeout 600s default; menu categories cached 24h"
    ]
  },
  "links": {
    "github": "https://github.com/alexisTrejo11/restaurant-managemenet-api",
    "demo": "https://{{YOUR_DEPLOYED_HOST}}/api/docs/",
    "documentation": "https://{{YOUR_DEPLOYED_HOST}}/api/docs/",
    "dockerHub": null
  },
  "mediaGallery": {
    "title": "Restaurant Management API — product views",
    "items": [
      {
        "type": "image",
        "url": "https://placehold.co/1200x630/1a1a2e/f5f5f5?text=Restaurant+Management+API",
        "thumbnail": "https://placehold.co/400x210/1a1a2e/f5f5f5?text=Restaurant+API",
        "title": "API cover",
        "description": "Restaurant Management REST API for menus, orders, tables, and payments",
        "alt": "Restaurant Management API branding placeholder",
        "category": "screenshot"
      },
      {
        "type": "image",
        "url": "https://placehold.co/1200x800/316192/ffffff?text=Swagger+OpenAPI",
        "thumbnail": "https://placehold.co/400x267/316192/ffffff?text=OpenAPI",
        "title": "OpenAPI documentation",
        "description": "Interactive API schema at /api/docs/ (drf-spectacular)",
        "alt": "OpenAPI Swagger UI placeholder",
        "category": "demo"
      }
    ],
    "description": "Replace placeholder image URLs with Swagger UI screenshots or admin dashboard captures from your deployed instance."
  },
  "mediaItems": [
    {
      "type": "image",
      "url": "https://placehold.co/800x500/37814A/ffffff?text=Architecture",
      "thumbnail": "https://placehold.co/320x200/37814A/ffffff?text=Arch",
      "title": "Service architecture",
      "description": "Django API in Docker with AWS RDS PostgreSQL and Upstash Redis",
      "alt": "Architecture diagram placeholder",
      "category": "architecture"
    },
    {
      "type": "image",
      "url": "https://placehold.co/800x500/DC382D/ffffff?text=Docker+Deploy",
      "thumbnail": "https://placehold.co/320x200/DC382D/ffffff?text=Docker",
      "title": "Docker deployment",
      "description": "docker-compose for local dev; production uses external RDS + Upstash",
      "alt": "Docker deployment placeholder",
      "category": "diagram"
    }
  ],
  "metrics": [
    {
      "label": "Django apps",
      "value": "9",
      "description": "Domain apps plus shared cross-cutting utilities"
    },
    {
      "label": "API version prefix",
      "value": "/api/v1/",
      "description": "All business endpoints under v1"
    },
    {
      "label": "Access token TTL",
      "value": "8 hours",
      "description": "SimpleJWT HS256 signing with JWT_SECRET_KEY"
    },
    {
      "label": "Default VAT rate",
      "value": "16%",
      "description": "PaymentCalculatorService.DEFAULT_VAT_RATE"
    },
    {
      "label": "Max reservation party",
      "value": "8",
      "description": "MAX_CUSTOMERS_PER_RESERVATION constant"
    }
  ]
} as unknown as ProjectOverview;
