// Auto-generated by parse-project-docs.js
import { ProjectCodeShowCase } from '../../../../../../core/models/project-docs.models';

export const codeShowcase = {
  "codeExamples": [
    {
      "id": "jwt-generation",
      "title": "JWT issuance with role claims",
      "description": "JWTService encodes subject (email) and roles list for Spring Security resource server consumption.",
      "category": "security",
      "duration": "3 min read",
      "views": 0,
      "tags": [
        "jwt",
        "security",
        "auth"
      ],
      "files": [
        {
          "name": "JWTService.java",
          "path": "src/main/java/.../service/JWTService.java",
          "language": "java",
          "highlighted": true,
          "explanation": "Tokens include issuer, expiry, subject, and roles claim stripped of ROLE_ prefix in authorities mapping.",
          "content": "public String generateToken(UserDetails userDetails) {\n    Instant now = Instant.now();\n    JwtClaimsSet claims = JwtClaimsSet.builder()\n            .issuer(\"alexisTrejo.expenses.tracking\")\n            .issuedAt(now)\n            .expiresAt(now.plusMillis(jwtExpirationMs))\n            .subject(userDetails.getUsername())\n            .claim(\"roles\", userDetails.getAuthorities().stream()\n                    .map(auth -> auth.getAuthority().replace(\"ROLE_\", \"\"))\n                    .toList())\n            .build();\n    return this.jwtEncoder.encode(JwtEncoderParameters.from(claims)).getTokenValue();\n}\n"
        }
      ]
    },
    {
      "id": "security-filter-chain",
      "title": "Path-based security rules",
      "description": "SecurityConfig declares public auth/swagger routes and role requirements per API prefix.",
      "category": "security",
      "duration": "4 min read",
      "views": 0,
      "tags": [
        "spring-security",
        "rbac"
      ],
      "files": [
        {
          "name": "SecurityConfig.java",
          "path": "src/main/java/.../config/security/SecurityConfig.java",
          "language": "java",
          "highlighted": true,
          "explanation": "Note FINANCIAL vs Role.FINANCE mismatch for reimbursement routes.",
          "content": ".authorizeHttpRequests(auth -> auth\n    .requestMatchers(\"/v1/api/auth/**\", \"/swagger-ui/**\", \"/api-docs/**\").permitAll()\n    .requestMatchers(\"/v1/api/admin/**\").hasRole(\"ADMIN\")\n    .requestMatchers(\"/v1/api/employees/**\").authenticated()\n    .requestMatchers(\"/v1/api/manager/**\").hasAnyRole(\"MANAGER\", \"ADMIN\")\n    .requestMatchers(\"/v1/api/reimbursements/**\").hasAnyRole(\"MANAGER\", \"FINANCIAL\")\n    .anyRequest().authenticated())\n.oauth2ResourceServer(oauth2 -> oauth2.jwt(jwt -> jwt\n    .decoder(jwtDecoder)\n    .jwtAuthenticationConverter(jwtAuthenticationConverter())));\n"
        }
      ]
    },
    {
      "id": "response-wrapper",
      "title": "Standard API response envelope",
      "description": "ResponseWrapper factory methods keep HTTP payloads consistent for clients.",
      "category": "api",
      "duration": "2 min read",
      "views": 0,
      "tags": [
        "api-design",
        "json"
      ],
      "files": [
        {
          "name": "ResponseWrapper.java",
          "path": "src/main/java/.../shared/ResponseWrapper.java",
          "language": "java",
          "highlighted": true,
          "explanation": "Fields: success, data, message, code, time_stamp.",
          "content": "public static <T> ResponseWrapper<T> success(T data, String message) {\n    return new ResponseWrapper<>(\n            true,\n            data,\n            message,\n            HttpStatus.OK.value(),\n            LocalDateTime.now()\n    );\n}\n"
        }
      ]
    },
    {
      "id": "rate-limit-interceptor",
      "title": "Global Bucket4j rate limiting",
      "description": "Every request consumes one token; exhaustion returns 429 JSON.",
      "category": "performance",
      "duration": "3 min read",
      "views": 0,
      "tags": [
        "bucket4j",
        "interceptor"
      ],
      "files": [
        {
          "name": "RateLimitInterceptor.java",
          "path": "src/main/java/.../config/rateLimiter/RateLimitInterceptor.java",
          "language": "java",
          "highlighted": true,
          "explanation": "Adds X-Rate-Limit-Remaining or X-Rate-Limit-Retry-After-Seconds headers.",
          "content": "ConsumptionProbe probe = bucket.tryConsumeAndReturnRemaining(1);\nif (!probe.isConsumed()) {\n    response.setStatus(HttpStatus.TOO_MANY_REQUESTS.value());\n    response.getWriter().write(\n        \"{ \\\"error\\\": \\\"You have exhausted your API Request Quota\\\", ... }\");\n    return false;\n}\n"
        }
      ]
    },
    {
      "id": "employee-expense-create",
      "title": "Submit expense with validation",
      "description": "EmployeeExpenseController validates DTO, creates PENDING expense, notifies stakeholders.",
      "category": "api",
      "duration": "4 min read",
      "views": 0,
      "tags": [
        "expenses",
        "workflow"
      ],
      "files": [
        {
          "name": "EmployeeExpenseController.java",
          "path": "src/main/java/.../controller/EmployeeExpenseController.java",
          "language": "java",
          "highlighted": true,
          "explanation": "Email taken from JWT via JWTService.getEmailFromRequest.",
          "content": "@PostMapping\npublic ResponseEntity<ResponseWrapper<ExpenseDTO>> requestExpense(\n        @Valid @RequestBody ExpenseInsertDTO insertDTO,\n        HttpServletRequest request) {\n    String email = jwtService.getEmailFromRequest(request);\n    Result<Void> validationResult = expenseService.validate(insertDTO);\n    if (!validationResult.isSuccess()) {\n        return ResponseEntity.status(HttpStatus.BAD_REQUEST)\n                .body(ResponseWrapper.badRequest(validationResult.getErrorMessage()));\n    }\n    ExpenseDTO expenseDTO = expenseService.createExpense(insertDTO, email, ExpenseStatus.PENDING);\n    notificationService.sendNotificationFromExpense(expenseDTO);\n    return ResponseEntity.status(HttpStatus.CREATED)\n            .body(ResponseWrapper.created(expenseDTO, \"Expense\"));\n}\n"
        }
      ]
    }
  ]
} as unknown as ProjectCodeShowCase;
