// Auto-generated by parse-project-docs.js
import { InfrastructureModel } from '../../../../../../core/models/project-docs.models';

export const infrastructure = {
  "deploymentLayers": [
    {
      "name": "Clients",
      "color": "#4F46E5",
      "components": [
        {
          "name": "Employee web / mobile app",
          "icon": "smartphone",
          "description": "Submits expenses and uploads receipts (future or separate frontend)"
        },
        {
          "name": "Manager dashboard",
          "icon": "layout",
          "description": "Approves/rejects queue, views summaries"
        },
        {
          "name": "Admin console",
          "icon": "settings",
          "description": "Settings and dashboard stats"
        }
      ]
    },
    {
      "name": "Application runtime",
      "color": "#059669",
      "components": [
        {
          "name": "Spring Boot JAR",
          "icon": "coffee",
          "description": "company-expenses-api boot jar on port 8080"
        },
        {
          "name": "Docker container (app)",
          "icon": "docker",
          "description": "Built from docker/Dockerfile via compose"
        },
        {
          "name": "Bucket4j interceptor",
          "icon": "gauge",
          "description": "Global rate limit on incoming HTTP"
        }
      ]
    },
    {
      "name": "Data layer",
      "color": "#DC2626",
      "components": [
        {
          "name": "PostgreSQL 15",
          "icon": "database",
          "description": "Local container in compose.local; external host in prod"
        },
        {
          "name": "Flyway",
          "icon": "migrate",
          "description": "Schema versioning at startup"
        },
        {
          "name": "Upload volume",
          "icon": "folder",
          "description": "Host path FILE_UPLOAD_DIR for attachments"
        }
      ]
    },
    {
      "name": "Integrations",
      "color": "#D97706",
      "components": [
        {
          "name": "SMTP",
          "icon": "mail",
          "description": "spring.mail.* from environment"
        },
        {
          "name": "OpenAPI / Swagger",
          "icon": "book",
          "description": "Public documentation endpoints"
        }
      ]
    }
  ],
  "dockerFiles": [
    {
      "service": "docker-compose.local.yml",
      "description": "Local development: Spring Boot app + PostgreSQL 15 with healthcheck and named volume.",
      "content": "services:\n  app:\n    build:\n      context: ..\n      dockerfile: docker/Dockerfile\n    ports:\n      - \"8080:8080\"\n    depends_on:\n      db:\n        condition: service_healthy\n    env_file:\n      - ../.env\n    environment:\n      DB_HOST: db\n      DB_PORT: \"5432\"\n  db:\n    image: postgres:15\n    ports:\n      - \"5431:5432\"\nvolumes:\n  postgres_data:\n"
    },
    {
      "service": "docker-compose.prod.yml",
      "description": "Production profile: app container only; DB_HOST points to external Postgres.",
      "content": "services:\n  app:\n    build:\n      context: ..\n      dockerfile: docker/Dockerfile\n    ports:\n      - \"8080:8080\"\n    env_file:\n      - ../.env\n    restart: unless-stopped\n"
    },
    {
      "service": "Dockerfile",
      "description": "Multi-stage: Gradle 8.5 JDK 17 build (skip tests), Temurin 17 JRE runs app.jar.",
      "content": "FROM gradle:8.5-jdk17 AS build\nWORKDIR /app\nCOPY . .\nRUN gradle build -x test\nFROM eclipse-temurin:17-jre-jammy\nCOPY --from=build /app/build/libs/*.jar app.jar\nEXPOSE 8080\nENTRYPOINT [\"java\", \"-jar\", \"app.jar\"]\n"
    }
  ],
  "cloudServices": [
    {
      "name": "PostgreSQL (managed or self-hosted)",
      "purpose": "Primary datastore for users, expenses, reimbursements, notifications, admin settings",
      "icon": "database",
      "cost": "~$0 local Docker — ~$15–50/mo managed (placeholder)"
    },
    {
      "name": "SMTP provider",
      "purpose": "Transactional email for notifications (MAIL_* in .env)",
      "icon": "mail",
      "cost": "Variable / free tier on many providers"
    },
    {
      "name": "Railway / Render / Fly.io (optional)",
      "purpose": "PaaS deploy using docker/Dockerfile and injected env vars per docker/README.md",
      "icon": "cloud",
      "cost": "Platform-dependent (placeholder)"
    },
    {
      "name": "Local filesystem",
      "purpose": "FILE_UPLOAD_DIR for receipt attachments (not S3 yet)",
      "icon": "folder",
      "cost": "$0"
    },
    {
      "name": "GitHub Actions (placeholder)",
      "purpose": "CI build and test — not configured in repo yet",
      "icon": "ci",
      "cost": "Free for public repos"
    }
  ],
  "metrics": [
    {
      "label": "API port",
      "value": "8080",
      "icon": "server",
      "description": "server.port in application.properties; exposed in Docker compose"
    },
    {
      "label": "Local Postgres host port",
      "value": "5431",
      "icon": "database",
      "description": "Maps container 5432 for host access during Gradle bootRun"
    },
    {
      "label": "Java runtime",
      "value": "17",
      "icon": "cpu",
      "description": "Eclipse Temurin JRE in production image"
    },
    {
      "label": "Flyway migrations",
      "value": "2",
      "icon": "migrate",
      "description": "V1 schema + V2 demo seed"
    }
  ]
} as unknown as InfrastructureModel;
