// Auto-generated by parse-project-docs.js
import { ProjectCodeShowCase } from '../../../../../../core/models/project-docs.models';

export const codeShowcase = {
  "codeExamples": [
    {
      "id": "jwt-token-validation",
      "title": "JWT validation with Redis blacklist",
      "description": "Every authenticated request passes through JwtService which rejects blacklisted tokens before parsing claims.",
      "category": "security",
      "duration": "3 min read",
      "views": 0,
      "tags": [
        "jwt",
        "redis",
        "auth"
      ],
      "files": [
        {
          "name": "JwtService.java",
          "path": "src/main/java/at/backend/tourist/places/modules/auth/jwt/JwtService.java",
          "language": "java",
          "highlighted": true,
          "explanation": "Blacklist check runs before JJWT parse; supports 6-char activation tokens via RedisTokenService.",
          "content": "public boolean validateToken(String token) {\n    if (token.length() == 6) {\n        return validateCustomerToken(token);\n    } else {\n        return validateJWTToken(token);\n    }\n}\n\nprivate boolean validateJWTToken(String token) {\n    if (redisTokenService.isTokenBlacklisted(token)) {\n        return false;\n    }\n    Jwts.parserBuilder()\n            .setSigningKey(getSigningKey())\n            .build()\n            .parseClaimsJws(token);\n    return true;\n}\n"
        }
      ]
    },
    {
      "id": "jwt-auth-filter",
      "title": "JWT authentication filter",
      "description": "OncePerRequestFilter extracts Bearer token, validates it, and populates SecurityContext.",
      "category": "security",
      "duration": "3 min read",
      "views": 0,
      "tags": [
        "spring-security",
        "filter"
      ],
      "files": [
        {
          "name": "JwtAuthenticationFilter.java",
          "path": "src/main/java/at/backend/tourist/places/modules/auth/jwt/JwtAuthenticationFilter.java",
          "language": "java",
          "highlighted": true,
          "explanation": "Runs before UsernamePasswordAuthenticationFilter; loads UserDetails from email claim.",
          "content": "@Override\nprotected void doFilterInternal(HttpServletRequest request,\n                                HttpServletResponse response,\n                                FilterChain filterChain) throws ServletException, IOException {\n    String token = extractToken(request);\n    if (token != null && jwtService.validateToken(token)) {\n        String email = jwtService.getEmailFromToken(token);\n        UserDetails userDetails = userService.loadUserByUsername(email);\n        UsernamePasswordAuthenticationToken authentication =\n                new UsernamePasswordAuthenticationToken(userDetails, null, userDetails.getAuthorities());\n        SecurityContextHolder.getContext().setAuthentication(authentication);\n    }\n    filterChain.doFilter(request, response);\n}\n"
        }
      ]
    },
    {
      "id": "response-wrapper",
      "title": "Standardized API response envelope",
      "description": "ResponseWrapper factory methods keep controller responses consistent for frontends and OpenAPI examples.",
      "category": "api",
      "duration": "2 min read",
      "views": 0,
      "tags": [
        "api",
        "responses"
      ],
      "files": [
        {
          "name": "ResponseWrapper.java",
          "path": "src/main/java/at/backend/tourist/places/core/shared/Response/ResponseWrapper.java",
          "language": "java",
          "highlighted": true,
          "explanation": "Static helpers: created(), found(), ok(), deleted(), badRequest(), notFound().",
          "content": "public static <T> ResponseWrapper<T> found(T data, String entity) {\n    String foundMsg = entity + \" data successfully fetched\";\n    return new ResponseWrapper<>(true, data, foundMsg, 200);\n}\n\npublic static <T> ResponseWrapper<T> created(T data, String entity) {\n    String createMsg = entity + \" successfully created\";\n    return new ResponseWrapper<>(true, data, createMsg, 201);\n}\n"
        }
      ]
    },
    {
      "id": "tourist-place-search",
      "title": "Paginated tourist place search",
      "description": "Controller builds Pageable from query DTO and delegates search to TouristPlaceService.",
      "category": "domain",
      "duration": "4 min read",
      "views": 0,
      "tags": [
        "places",
        "pagination"
      ],
      "files": [
        {
          "name": "TouristPlaceController.java",
          "path": "src/main/java/at/backend/tourist/places/modules/places/controller/TouristPlaceController.java",
          "language": "java",
          "highlighted": true,
          "explanation": "Public GET /search — sort direction and field come from TouristPlaceSearchDTO.",
          "content": "@GetMapping(\"/search\")\npublic ResponseWrapper<Page<TouristPlaceDTO>> searchTouristPlaces(\n        @ModelAttribute TouristPlaceSearchDTO searchDto) {\n    Sort sort = Sort.by(\n            searchDto.getSortDirection().equalsIgnoreCase(\"desc\") ?\n                    Sort.Direction.DESC : Sort.Direction.ASC,\n            searchDto.getSortBy());\n    Pageable pageable = PageRequest.of(searchDto.getPage(), searchDto.getSize(), sort);\n    Page<TouristPlaceDTO> results = placeService.searchTouristPlaces(searchDto, pageable);\n    return ResponseWrapper.found(results, \"Tourist places\");\n}\n"
        }
      ]
    },
    {
      "id": "country-caffeine-cache",
      "title": "Caffeine cache for country reads",
      "description": "CacheConfig registers named caches with 1-day expire-after-access for browse-heavy country endpoints.",
      "category": "performance",
      "duration": "2 min read",
      "views": 0,
      "tags": [
        "caching",
        "caffeine"
      ],
      "files": [
        {
          "name": "CacheConfig.java",
          "path": "src/main/java/at/backend/tourist/places/core/config/CacheConfig.java",
          "language": "java",
          "highlighted": true,
          "explanation": "Four cache names for country query patterns; max 100 entries each.",
          "content": "@Bean\npublic CacheManager cacheManager() {\n    CaffeineCacheManager cacheManager = new CaffeineCacheManager(\n            \"countryById\", \"allCountries\",\n            \"countriesByContinent\", \"countryByName\");\n    cacheManager.setCaffeine(Caffeine.newBuilder()\n            .maximumSize(100)\n            .expireAfterAccess(1, TimeUnit.DAYS));\n    return cacheManager;\n}\n"
        }
      ]
    },
    {
      "id": "security-config",
      "title": "Spring Security filter chain",
      "description": "Defines public auth/swagger routes, permissive GET access, and JWT filter placement.",
      "category": "security",
      "duration": "4 min read",
      "views": 0,
      "tags": [
        "security",
        "spring"
      ],
      "files": [
        {
          "name": "SecurityConfig.java",
          "path": "src/main/java/at/backend/tourist/places/core/config/SecurityConfig.java",
          "language": "java",
          "highlighted": true,
          "explanation": "CSRF disabled; stateless sessions; OAuth2 login for Google; review GET permitAll implications before prod.",
          "content": "http.csrf(AbstractHttpConfigurer::disable)\n    .authorizeHttpRequests(auth -> auth\n        .requestMatchers(\"/signup\", \"/login\", \"/auth/**\").permitAll()\n        .requestMatchers(\"/v3/api-docs/**\", \"/swagger-ui/**\").permitAll()\n        .requestMatchers(HttpMethod.GET, \"/**\").permitAll()\n        .anyRequest().authenticated())\n    .sessionManagement(s -> s.sessionCreationPolicy(SessionCreationPolicy.STATELESS))\n    .addFilterBefore(jwtAuthFilter, UsernamePasswordAuthenticationFilter.class);\n"
        }
      ]
    }
  ]
} as unknown as ProjectCodeShowCase;
