// Auto-generated by parse-project-docs.js
import { ProjectFeatures } from '../../../../../../core/models/project-docs.models';

export const features = {
  "features": [
    {
      "id": "jwt-auth-rbac",
      "title": "JWT authentication & role-based access",
      "description": "Email login with SimpleJWT access/refresh tokens, custom claims (user_type, full_name), and DRF permissions for patient, specialist, staff, and admin flows.",
      "icon": "shield-lock",
      "category": "authentication",
      "status": "stable",
      "highlights": [
        "Login rate-limited per email (5/min)",
        "Account activation and password reset via cache tokens",
        "Admin user management at /api/v2/auth/users/"
      ],
      "techStack": [
        "djangorestframework-simplejwt",
        "apps/users",
        "apps/core/permissions.py"
      ],
      "metrics": [
        {
          "label": "Access token TTL",
          "value": "60 min",
          "trend": "stable",
          "icon": "clock"
        },
        {
          "label": "Refresh token TTL",
          "value": "7 days",
          "trend": "stable",
          "icon": "refresh"
        }
      ],
      "codeSnippet": {
        "language": "python",
        "filename": "apps/users/views/auth_views.py",
        "code": "@rate_limit(profile=\"SENSITIVE\", scope=\"login\")\ndef post(self, request):\n    user, tokens = UserService.authenticate_user(email, password)\n    return APIResponse.success(data={\"user\": ..., \"tokens\": tokens})\n"
      }
    },
    {
      "id": "specialist-scheduling",
      "title": "Specialist profiles & availability",
      "description": "Public discovery of psychologists, psychiatrists, and therapists with services, categories, and date-based available slots for patient booking.",
      "icon": "calendar-heart",
      "category": "api",
      "status": "stable",
      "highlights": [
        "Public GET /api/v2/specialists/ and available-slots",
        "Staff/admin manage specialists and clinic services",
        "Weekly availability model per specialist"
      ],
      "techStack": [
        "apps/specialists",
        "Django ORM"
      ],
      "metrics": [
        {
          "label": "Public list rate",
          "value": "30/min IP",
          "trend": "stable",
          "icon": "gauge"
        }
      ]
    },
    {
      "id": "appointments-engine",
      "title": "Appointment booking rules",
      "description": "Service-layer validation for clinic hours, booking windows, overlaps, and role-scoped querysets for patients and specialists.",
      "icon": "calendar-check",
      "category": "api",
      "status": "stable",
      "highlights": [
        "Clinic hours 09:00–19:00",
        "Cancel, reschedule, today, and stats actions",
        "Virtual session and room fields on Appointment model"
      ],
      "techStack": [
        "apps/appointments/services.py"
      ],
      "metrics": [
        {
          "label": "Max advance booking",
          "value": "90 days",
          "trend": "stable",
          "icon": "calendar"
        }
      ],
      "codeSnippet": {
        "language": "python",
        "filename": "apps/appointments/services.py",
        "code": "CLINIC_OPEN_HOUR = 9\nCLINIC_CLOSE_HOUR = 19\nMIN_ADVANCE_BOOKING_HOURS = 1\nMAX_ADVANCE_BOOKING_DAYS = 90\n"
      }
    },
    {
      "id": "medical-records-privacy",
      "title": "Confidential medical records",
      "description": "Clinical notes tied to appointments with standard, sensitive, and highly_sensitive levels; patients blocked from highly_sensitive; 24h specialist edit window.",
      "icon": "file-medical",
      "category": "security",
      "status": "stable",
      "highlights": [
        "MedicalRecordService access matrix by role",
        "Export and audit-log endpoints for compliance workflows",
        "Change-confidentiality action for admin/staff"
      ],
      "techStack": [
        "apps/medical",
        "django-encrypted-model-fields (dependency)"
      ],
      "metrics": [
        {
          "label": "Edit window",
          "value": "24 hours",
          "trend": "stable",
          "icon": "edit"
        }
      ]
    },
    {
      "id": "billing-stripe",
      "title": "Billing, invoices & Stripe",
      "description": "Bills from appointments, cash and bank-transfer payments, Stripe PaymentIntents, refunds, insurance claims, and PDF invoices.",
      "icon": "credit-card",
      "category": "integration",
      "status": "stable",
      "highlights": [
        "my-bills and overdue listings for patients",
        "Invoice PDF and email reminders",
        "Stripe webhook handler implemented (route pending)"
      ],
      "techStack": [
        "stripe",
        "reportlab",
        "apps/billing"
      ],
      "metrics": [
        {
          "label": "Payment channels",
          "value": "3+",
          "trend": "up",
          "icon": "wallet"
        }
      ]
    },
    {
      "id": "rate-limiting",
      "title": "Redis-backed rate limiting",
      "description": "Profile-based sliding window limits (SENSITIVE, PUBLIC, WRITE_OPERATION, etc.) using Django cache / Redis.",
      "icon": "speedometer",
      "category": "performance",
      "status": "stable",
      "highlights": [
        "Per-email login throttling",
        "Per-IP public endpoint protection",
        "Configurable profiles in apps/core/decorators/profiles.py"
      ],
      "techStack": [
        "django-redis",
        "apps/core/decorators/rate_limit.py"
      ],
      "codeSnippet": {
        "language": "python",
        "filename": "apps/core/decorators/profiles.py",
        "code": "SENSITIVE = {\"key_type\": \"email\", \"rate\": \"5/1min\", ...}\nPUBLIC = {\"key_type\": \"ip\", \"rate\": \"30/1min\", ...}\n"
      }
    },
    {
      "id": "notifications-async",
      "title": "Multi-channel notifications",
      "description": "Email and SMS templates with Celery tasks for appointment reminders, activation, and billing—notification app present; HTTP admin API not mounted in urls.",
      "icon": "bell",
      "category": "messaging",
      "status": "beta",
      "highlights": [
        "NotificationTemplate and user preferences models",
        "Celery beat: process-pending-notifications",
        "Twilio and SMTP configuration via environment"
      ],
      "techStack": [
        "Celery",
        "Twilio",
        "apps/notification"
      ]
    },
    {
      "id": "openapi-docs",
      "title": "OpenAPI & standardized responses",
      "description": "drf-spectacular schema, Swagger UI, ReDoc, and uniform APIResponse envelope for success and errors.",
      "icon": "book",
      "category": "api",
      "status": "stable",
      "highlights": [
        "/api/v2/schema/swagger-ui/",
        "MindCareBaseException global handling",
        "AuditLoggingMiddleware for sensitive actions"
      ],
      "techStack": [
        "drf-spectacular",
        "apps/core/responses/api_response.py"
      ],
      "metrics": [
        {
          "label": "Documented version",
          "value": "2.0.0",
          "trend": "stable",
          "icon": "tag"
        }
      ]
    },
    {
      "id": "docker-production",
      "title": "Docker production image",
      "description": "Multi-stage Python 3.11 image, non-root django user, entrypoint migrations, and Gunicorn WSGI server for EC2 or ECS deploy.",
      "icon": "docker",
      "category": "integration",
      "status": "stable",
      "highlights": [
        "Waits for cloud PostgreSQL and Redis",
        "Optional POPULATE_DUMMY_DATA and CREATE_SUPERUSER",
        "Host port 8001 → container 8000"
      ],
      "techStack": [
        "Docker",
        "Gunicorn",
        "docker/docker-compose.yml"
      ]
    }
  ]
} as unknown as ProjectFeatures;
