// Auto-generated by parse-project-docs.js
import { InfrastructureModel } from '../../../../../../core/models/project-docs.models';

export const infrastructure = {
  "deploymentLayers": [
    {
      "name": "Clients",
      "color": "#4F46E5",
      "components": [
        {
          "name": "Clinic admin web app",
          "icon": "layout",
          "description": "Staff dashboard (future or separate frontend) calling REST API"
        },
        {
          "name": "Patient portal / mobile",
          "icon": "smartphone",
          "description": "Books appointments and pays bills via JWT-authenticated API"
        },
        {
          "name": "Therapist tools",
          "icon": "user-md",
          "description": "Specialists manage schedule, notes, and services"
        }
      ]
    },
    {
      "name": "Edge & compute (EC2)",
      "color": "#059669",
      "components": [
        {
          "name": "Nginx / ALB (recommended)",
          "icon": "globe",
          "description": "TLS termination, reverse proxy to Gunicorn on port 8001"
        },
        {
          "name": "Docker — mindcare_api",
          "icon": "docker",
          "description": "Built from docker/dockerfile; ENVIRONMENT=production"
        },
        {
          "name": "Celery worker (optional same host)",
          "icon": "worker",
          "description": "Processes notification and async billing tasks"
        }
      ]
    },
    {
      "name": "Data & messaging",
      "color": "#DC2626",
      "components": [
        {
          "name": "RDS PostgreSQL",
          "icon": "database",
          "description": "at_mind_care_hub_db — all Django models"
        },
        {
          "name": "Upstash Redis",
          "icon": "redis",
          "description": "Cache prefix mind_care_hub, 900s default timeout"
        },
        {
          "name": "Local volume logs",
          "icon": "folder",
          "description": "logs_volume mounted at /app/logs in container"
        }
      ]
    },
    {
      "name": "External integrations",
      "color": "#D97706",
      "components": [
        {
          "name": "Stripe API",
          "icon": "credit-card",
          "description": "PaymentIntents and webhook signatures"
        },
        {
          "name": "Email SMTP",
          "icon": "mail",
          "description": "Transactional email from DEFAULT_FROM_EMAIL"
        },
        {
          "name": "Twilio SMS",
          "icon": "message",
          "description": "TWILIO_* env vars for SMS delivery"
        }
      ]
    }
  ],
  "dockerFiles": [
    {
      "service": "web (docker-compose)",
      "description": "Single-service compose file; PostgreSQL and Redis are external cloud instances, not containerized.",
      "content": "services:\n  web:\n    build:\n      context: ..\n      dockerfile: docker/dockerfile\n    container_name: mindcare_api\n    env_file: ../.env\n    environment:\n      DJANGO_SETTINGS_MODULE: config.settings.production\n      ENVIRONMENT: production\n    ports:\n      - \"8001:8000\"\n    volumes:\n      - logs_volume:/app/logs\n    restart: unless-stopped\n# Cloud: RDS PostgreSQL + Upstash Redis\n"
    },
    {
      "service": "dockerfile (multi-stage)",
      "description": "Python 3.11 slim bookworm; builder installs requirements; runtime runs as non-root django user.",
      "content": "FROM python:3.11-slim-bookworm AS builder\n# gcc, libpq-dev, pip install -r requirements.txt\nFROM python:3.11-slim-bookworm AS runtime\nUSER django\nEXPOSE 8000\nENTRYPOINT [\"/bin/sh\", \"/app/scripts/entrypoint.sh\"]\n# Gunicorn: 3 workers, 2 threads, migrate on start\n"
    },
    {
      "service": "entrypoint.sh",
      "description": "Waits for DB_HOST/REDIS_HOST, runs migrate, optional superuser/dummy data, starts Gunicorn.",
      "content": "# nc -z DB_HOST DB_PORT  (PostgreSQL ready)\n# nc -z REDIS_HOST REDIS_PORT  (Redis ready)\npython manage.py migrate --noinput\ngunicorn config.wsgi:application --bind 0.0.0.0:${PORT:-8000} --workers 3 --threads 2\n"
    }
  ],
  "cloudServices": [
    {
      "name": "Amazon EC2",
      "purpose": "Runs Docker Compose web service (mindcare_api) for the Django API behind security group allowing 8001/443",
      "icon": "aws-ec2",
      "cost": "~$15–40/mo (t3.small placeholder)"
    },
    {
      "name": "Amazon RDS (PostgreSQL)",
      "purpose": "Managed primary database for users, appointments, medical records, and billing (DB_HOST in .env)",
      "icon": "aws-rds",
      "cost": "~$25–80/mo (db.t4g.micro placeholder)"
    },
    {
      "name": "Upstash Redis",
      "purpose": "Cache (DB 1), rate limiting, activation tokens, and Celery broker URL (REDIS_HOST / REDIS_URL)",
      "icon": "redis",
      "cost": "Free tier or ~$10/mo"
    },
    {
      "name": "Stripe",
      "purpose": "Online card payments, PaymentIntents, and webhooks for billing reconciliation",
      "icon": "stripe",
      "cost": "2.9% + per transaction"
    },
    {
      "name": "SMTP (e.g. Gmail / SES)",
      "purpose": "Account activation, password reset, invoice and reminder emails",
      "icon": "mail",
      "cost": "Variable / SES low volume"
    },
    {
      "name": "Twilio",
      "purpose": "SMS notifications for appointments and system alerts",
      "icon": "twilio",
      "cost": "Per SMS"
    },
    {
      "name": "Sentry (optional)",
      "purpose": "Error tracking when SENTRY_DSN is set in production",
      "icon": "sentry",
      "cost": "Free tier available"
    }
  ],
  "metrics": [
    {
      "label": "Container port",
      "value": "8000",
      "icon": "server",
      "description": "Gunicorn binds 0.0.0.0:8000 inside the web container"
    },
    {
      "label": "Host mapping",
      "value": "8001:8000",
      "icon": "network",
      "description": "docker-compose publishes API on host port 8001 for EC2 security groups"
    },
    {
      "label": "Gunicorn workers",
      "value": "3 × 2 threads",
      "icon": "cpu",
      "description": "scripts/entrypoint.sh — tune per EC2 instance size"
    },
    {
      "label": "DB connection pool",
      "value": "600s",
      "icon": "database",
      "description": "CONN_MAX_AGE in production PostgreSQL settings"
    }
  ]
} as unknown as InfrastructureModel;
